### ISSUE TITLE
gosseract go build error

### ISSUE THREAD

**Issue by rajasekar1** [otiai10/gosseract#100]
Hi,

I am using ubuntu with docker, In my code i importe gosseract package.
When i try to build application. I got below error.

```
om build: 2 "# ./vendor/github.com/otiai10/gosseract
/usr/bin/ld: cannot find -llept
/usr/bin/ld: cannot find -ltesseract
/usr/bin/ld: cannot find -llept
/usr/bin/ld: cannot find -ltesseract
collect2: error: ld returned 1 exit status
```

**Comment by otiai10** [comment]
please follow https://github.com/otiai10/gosseract/blob/master/ISSUE_TEMPLATE.md

**Comment by otiai10** [comment]
at least I want to know which OS you are using. if there is no longer response, I would close this issue by 24H

**Comment by rajasekar1** [comment]
We have using Ubuntu 16.8. It seems C++ file link problem.

**Comment by otiai10** [comment]
@rajasekar1 OK, thanks, then please follow this template https://github.com/otiai10/gosseract/blob/master/ISSUE_TEMPLATE.md
