### ISSUE TITLE
How can i add blacklist?

### ISSUE THREAD

**Issue by liyuliang2013** [otiai10/gosseract#118]
I have some code picture with number, so i want to pass all letter

**Comment by otiai10** [comment]
I didn't got what you mean. Do you want `blacklist`, or `whitelist`?

**Comment by liyuliang2013** [comment]
I want blacklist to filter all letter

**Comment by liyuliang2013** [comment]
oh! I found the whitelist method! thanks!

**Comment by otiai10** [comment]
Anyway, I have to imple blacklist. Thanks for opening this issue 😉

**Comment by liyuliang2013** [comment]
Thanks a lot, it's very helpful
