### ISSUE TITLE
go build failed in Ubuntu 14.04

### ISSUE THREAD

**Issue by liyuliang2013** [otiai10/gosseract#122]
# Summary

- I meet the error ``/usr/include/c++/4.9/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
``

# Reproducibility

## Reproducility Frequency

- 100%

# Environment

```
# uname -a
Linux app 4.15.5-041505-generic #201802221031 SMP Thu Feb 22 15:32:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build174351498=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"```

```
# go version
go version go1.8 linux/amd64
```

```
# tesseract --version
tesseract 4.0.0-beta.1
 leptonica-1.75.3
  libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8 : libwebp 0.4.0

 Found AVX
 Found SSE
```

**Comment by liyuliang2013** [comment]
um.. i found the solution. thanks

**Comment by otiai10** [comment]
Could you write down the causes and solutions for one who follow you :)
