### ISSUE TITLE
Tesseract BaseAPI memory leak

### ISSUE THREAD

**Issue by ansonl** [otiai10/gosseract#124]
Continued from #123...

There seems to be a memory leak issue in the Tesseract BaseAPI.End() function. When calling the End() function and letting client go out of scope, memory usage decreases slightly, but still takes up a couple megabytes of memory for each client struct created.

This can be seen by running the below test program:

```go
package main

import (
	"fmt"
	"github.com/otiai10/gosseract"
	"time"
)

func main() {

	var count int

	var clients []*gosseract.Client

	for _ = range time.Tick(time.Millisecond * 100) {
		client := gosseract.NewClient()

		client.SetImage("002-confusing.png")
		text, _ := client.Text()
		_, _ = client.HOCRText()
		fmt.Println(text)
		// Hello, World!
		count++

		clients = append(clients, client)

		if count == 20 {
			break
		}
	}

	for _ = range time.Tick(time.Millisecond * 10) {
		count--
		if count == 0 {
			break
		}
	}

	for _, c := range clients {
		(*c).Close()
	}

	for _ = range time.Tick(time.Second * 1) {
	}
}
```

For some reason, after the clients are closed and the tesseract BaseAPI End() method should be called, memory usage will remain elevated. I have tried calling the Go garbage collector functions and it seems to make no difference. The only way I have found to release the memory is to exit the program.

I looked through the gosseract library .cpp file and have not seen any bugs, so this may be a tesseract library issue.

Tesseract BaseAPI End method reference: https://zdenop.github.io/tesseract-doc/group___advanced_a_p_i.html#ga38027513ee9c0348de1790bddcdc3391

**Comment by otiai10** [comment]
at least, I guess you are leaking Ticker channel

**Comment by otiai10** [comment]
`clients` slice is not garbage. It's still in scope.

I used pprof and it takes 1MB for the slice even with 500 structs long.
https://gist.github.com/otiai10/cfdc68d20c78b094ef4508adf27afdbe

How did you figure out that

> a couple megabytes of memory for each client struct

?

**Comment by will7200** [comment]
I also detected a memory leak in one of my programs, that is long running and it is prevalent. I did some further digging and it appears that tesseract does not take ownership of Pix images set to, hence it is up to the users the destroy those objects.

You can find a old doc for 3.02 [here](https://zdenop.github.io/tesseract-doc/group___advanced_a_p_i.html#ga953b401286da174e609f09c5f275734e)

It is also possibly wise to call tesseract::TessBaseAPI::Clear on client close as well.
[Here](https://github.com/tesseract-ocr/tesseract/wiki/APIExample) is a sample c++ of destorying pix.

**Comment by otiai10** [comment]
@will7200 Thank you very much!

**Comment by will7200** [comment]
@otiai10 Users might also want to clear cached data well, 
ClearPersistentCache()
