### ISSUE TITLE
How do I use a training set with Gosseract?

### ISSUE THREAD

**Issue by gislikarl** [otiai10/gosseract#125]
What do I need to to in order to use a training set with Gosseract?

**Comment by otiai10** [comment]
do you mean these?

- https://github.com/otiai10/gosseract/blob/master/test/runtimes/Quickstart.Dockerfile#L7-L10
- https://github.com/otiai10/gosseract/blob/master/all_test.go#L89

**Comment by gislikarl** [comment]
No I mean something like creating a training set for a different set of fonts. But I think I found what I'm looking for so thank you anyways.

**Comment by otiai10** [comment]
@gislikarl Thank you too.
If you don't mind, share the links here so that someone else can get what you were looking for.

**Comment by quickrworld** [comment]
Training should be done for tesseract. The documentation is located [here](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00).
Gosseract will derive the benefits since it calls tesseract under the covers.
