### ISSUE TITLE
Installation Failure on Windows 7 

### ISSUE THREAD

**Issue by vsarin** [otiai10/gosseract#132]
# Summary
Installation Failure on Windows 7 
λ go get -t github.com/otiai10/gosseract
# github.com/otiai10/gosseract
tessbridge.cpp:5:10: fatal error: tesseract/baseapi.h: No such file or directory
 #include <tesseract/baseapi.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
# Reproducibility
Yes
## Reproducility Frequency

- 100%

## Reproducible Dockerfile

```dockerfile
FROM your-os:your-version
# Describe how to reproduce your problem
# on your environment
```

Otherwise, describe how to reproduce

1. Install GO lan
2. Install GCC (64 Bit Compiler)
3. Install GIT
4. Install Tesseract from this site
https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-setup-3.05.02-20180621.exe
5. Execute 
λ go get -t github.com/otiai10/gosseract
# github.com/otiai10/gosseract
tessbridge.cpp:5:10: fatal error: tesseract/baseapi.h: No such file or directory
 #include <tesseract/baseapi.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
# Environment
Windows 7 
```
uname -a
```

```
go env
```
C:\Users\33133
λ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\33133\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\33133\go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\33133\AppData\Local\Temp\go-build238513982=/tmp/go-build -gno-record-gcc-switches

C:\Users\33133
λ
```
go version
```
λ go version
go version go1.10.3 windows/amd64
```
tesseract --version
```
C:\Program Files (x86)\Tesseract-OCR>tesseract --version
tesseract 3.05.02
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.
9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.2.0

C:\Program Files (x86)\Tesseract-OCR>

**Comment by javafoo** [comment]
same problem here.

**Comment by imbananko** [comment]
Same for me
Any luck with the resolution?

**Comment by xgz123** [comment]
Same for me
Need help!

**Comment by EgeBalci** [comment]
Same here.

```
github.com/otiai10/gosseract
# github.com/otiai10/gosseract
tessbridge.cpp:5:10: fatal error: tesseract/baseapi.h: No such file or directory
 #include <tesseract/baseapi.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by aliforever** [comment]
go get -t github.com/otiai10/gosseract
# github.com/otiai10/gosseract
tessbridge.cpp:5:10: fatal error: tesseract/baseapi.h: No such file or directory
 #include <tesseract/baseapi.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Same, on Windows 10

**Comment by otiai10** [comment]
did you install header files as well?

**Comment by cenav** [comment]
No, i didn't

El 17 ene. 2019 2:04 a.m., "Hiromu OCHIAI" <notifications@github.com>
escribió:

did you install header files as well?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/otiai10/gosseract/issues/132#issuecomment-455064415>,
or mute the thread

**Comment by aliforever** [comment]
> did you install header files as well?

I have installed Tesseract, don't know about header files,. How do I install them on windows?

**Comment by aliforever** [comment]
If anyone has the same problem, you could use below command as a replacement for the library until a fix comes:
```
cmd := exec.Command(`C:\Program Files\Tesseract-OCR\tesseract.exe`, "image_name", "output")
```
It saves the result in output.txt file

**Comment by otiai10** [comment]
Just for your information 👉 https://github.com/otiai10/gosseract/pull/21

I'm gonna keep working on this request: Nicer tutorial for using this package on Windows.

Thank you anyway.

**Comment by xiaodi2015** [comment]
hope someone can solve this problem earlier.

**Comment by moolen** [comment]
It's great to see windows users! I tried to install it on windows, too. It was a hell of a ride. We could ship a `includes/` directory with this repo which contains the header files for tesseract and leptonica. That let's gosseract compile.

For the linkage, however, the user still has to grab or compile tesseract and libleptonica. The latter is not packaged for windows yet and is a pain to get it compiled.

A proper CI integration is a whole other topic for windows :roll_eyes:

**Comment by moolen** [comment]
I got a first (native) build on windows working :tada:
It's a simple `gosseract.Version()` call but it's using the C interface under the hood.

changes in a nutshell:
* provide `includes/` dir in the gosseract repo
* build & provide dlls for leptonica & tesseract
* link against those libs
* add tesseract dir to `$PATH` (for remaining shared libs)

I'm not sure where to go from here. I don't want to expect users to install a full MSVC toolchain to compile leptonica. Also, i don't want to provide a MSI.

There are [binaries for windows](https://github.com/tesseract-ocr/tesseract/wiki/Downloads) at least.

I'll ask upstream if they see a value to have a precompiled dll then we might be able to leverage that.

![Imgur](https://i.imgur.com/i5I0Qx1.jpg)

**Comment by lluck42** [comment]
i hava the save problem in win 10. and i don't find any *.h file in tesseract-ocr dir.

**Comment by wangsongyan** [comment]
> I'll ask upstream if they see a value to have a precompiled dll then we might be able to leverage that.
I'm in trouble with compling this repo on windows 10, need your help

**Comment by moolen** [comment]
@wangsongyan here's roughly what i did. Please let me know if that helps you.

#### Prerequisites

* [Go build toolchain on windows](https://github.com/golang/go/wiki/WindowsBuild#the-manual-way)

Grab the Tesseract precompiled binaries from: https://github.com/UB-Mannheim/tesseract/wiki
download & extract it to `$GOPATH/src/github.com/otiai10/gosseract/tesseract`

Grab leptonica sources from [here](https://github.com/DanBloomberg/leptonica) and build a 64bit dll using cppan. [This gives you hints](https://github.com/tvn-cosine/leptonica.net/wiki/Compiling-the-Leptonica-lib-for-Windows).

Grab the header files from your linux box (`/usr/include/tesseract` and `/usr/include/leptonica`) and copy them to this repo to `$REPO/includes`.

change `client.go` to include the headers and also tell the linker where the:
```
// #cgo CXXFLAGS: -std=c++0x -I./include
// #cgo LDFLAGS: -Ltesseract -Lleptonica/build64/bin/Release -lleptonica-1.78.0 -llibtesseract-4
```

This is how the repo should look once you have everything in place:
```
$GOPATH/github.com/otiai10/gosseract
├── include
│    ├── tesseract/*.h
│    └── leptonica/*.h
├── tesseract/libtesseract-4.dll
└── leptonica/build64/bin/Release/leptonica-1.78.0.dll
```

(!) Also, make sure, that `$REPO/tesseract/` aswell as `$REPO/leptonica/build64/bin/Release` is in your `$PATH`.

#### Test program
```go
package main

import (
    "log"

    "github.com/otiai10/gosseract"
)

func main() {
    log.Println(gosseract.Version())
}

```

Test if we are able to compile, link and execute it.
```
$ go build cmd/main.go
$ ./main.exe
2019/05/07 xxxx v4.0.0.20190314
```

**Comment by wangsongyan** [comment]
@moolen Thank you very much! According to your method, I have run successfully.

**Comment by mjarkk** [comment]
I had the same issue on fedora (linux),  
I've solved it by installing: `tesseract-devel`  
For the Ubuntu this is: `libtesseract-dev`

**Comment by otiai10** [comment]
See https://github.com/otiai10/gosseract/tree/master/test/runtimes for linux runtimes

**Comment by veryWrong** [comment]
@moolen 
I did what you said, but I got the mistake:
Process finished with exit code -1073741511 (0xC0000139)

**Comment by moolen** [comment]
@veryWrong According to the [MS docs](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55?redirectedfrom=MSDN) 
> The procedure entry point [...] could not be located in the dynamic link library

I assume that the `-lleptonica-X-XX.X` and `-llibtesseract-X` in
```
// #cgo LDFLAGS: -Ltesseract -Lleptonica/build64/bin/Release -lleptonica-1.78.0 -llibtesseract-4
```
do not match with the entry points defined in the `.dll` files.
I'd suggest taking a look at the leptonica and tesseract dlls `objdump -p xxx.dll`.

**Comment by veryWrong** [comment]
> @veryWrong According to the [MS docs](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55?redirectedfrom=MSDN)
> 
> > The procedure entry point [...] could not be located in the dynamic link library
> 
> I assume that the `-lleptonica-X-XX.X` and `-llibtesseract-X` in
> 
> ```
> // #cgo LDFLAGS: -Ltesseract -Lleptonica/build64/bin/Release -lleptonica-1.78.0 -llibtesseract-4
> ```
> 
> do not match with the entry points defined in the `.dll` files.
> I'd suggest taking a look at the leptonica and tesseract dlls `objdump -p xxx.dll`.

Can you upload your project demo to Github ? Thanks

**Comment by moolen** [comment]
> @moolen
> Can you upload your project demo to Github ? Thanks

sorry, i deleted that VM a while ago :(

**Comment by veryWrong** [comment]
> > @moolen
> > Can you upload your project demo to Github ? Thanks
> 
> sorry, i deleted that VM a while ago :(

> My problem has been solved, thank you for your help

**Comment by otiai10** [comment]
@veryWrong 
Can you please share how you managed this problem?

**Comment by veryWrong** [comment]
> @veryWrong
> Can you please share how you managed this problem?
Of course, Here are my actions：
- As moolen said: 
> 1. Grab the header files from your linux box (/usr/include/tesseract and /usr/include/leptonica) and copy them to this repo to $REPO/includes.
> 2. Grab the Tesseract precompiled binaries from: https://github.com/UB-Mannheim/tesseract/wiki
download & extract libtesseract-4.dll to $GOPATH/src/github.com/otiai10/gosseract/tesseract & extract liblept-5.dll to $GOPATH/src/github.com/otiai10/gosseract/lept
> 3. Add environment variable `TESSDATA_PREFIX` testdata path
> 4. change client.go to include the headers and also tell the linker where the:
```
// #cgo linux CXXFLAGS: -std=c++0x
// #cgo linux LDFLAGS: -L/usr/local/lib -llept -ltesseract
// #cgo windows CXXFLAGS: -std=c++0x -Iinclude
// #cgo windows LDFLAGS: -Ltesseract -llibtesseract-4 -Llept -lliblept-5
```
- Now run go build and copy Tesseract-OCR/*.dll to the same directory as the cmd.exe, don't run through `go run main.go`

there is my demo: https://github.com/veryWrong/gosseract-win-demo

**Comment by otiai10** [comment]
Very appreciated 👍
