### ISSUE TITLE
macOS complie linux binary file failed

### ISSUE THREAD

**Issue by czh0318** [otiai10/gosseract#138]
# Summary
I'm using macOS and  going to compile binary file for centos7.1, and build failed, show message: undefined: gosseract.NewClient.
Thanks. 

# Reproducibility

## Reproducility Frequency

100%

# Environment

```
uname -a
```
Darwin AllenChen-MacBookPro.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64
```
go env
```
GOARCH="amd64"
GOBIN="/Users/allen/Documents/go/bin"
GOCACHE="/Users/allen/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/allen/Documents/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s6/mqbnh2yn52b5glrvhk53jyxh0000gn/T/go-build032873897=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
go version
```
go version go1.11 darwin/amd64
```
tesseract --version
```
tesseract 4.0.0
 leptonica-1.76.0
  libjpeg 9c : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.11
 Found AVX
 Found SSE

**Comment by czh0318** [comment]
Thank you very much, I have solved this problem.

**Comment by markschmid** [comment]
@czh0318 How did you solve this problem? I'm having exactly the same issue and am very interested in a solution.

**Comment by otiai10** [comment]
@markschmid I am very interested in what you are facing.I still don't figure out what the problem is. Could you give me command-by-command log?

**Comment by markschmid** [comment]
@otiai10 We were facing the same `undefined: gosseract.NewClient.` error message when compiling our .go files. In the meantime, we were able to resolve it by changing `CGO_ENABLED=0` to `CGO_ENABLED=1`

We're trying to build a very minimal docker container with just what's really needed from tesseract (version 4) and our standalone application binary (cross compiled from our .go files).

Maybe you could extend your (otherwise great) runtime templates with an example? Help is greatly appreciated!

**Comment by lranasingha** [comment]
Setting `CGO_ENABLED` to `1` solved the docker build failure caused by `undefined: gosseract.NewClient` for me too.

**Comment by timelxy** [comment]
Setting CGO_ENABLED to 1 works for me too.
