### ISSUE TITLE
Does not return the position of each word location ?

### ISSUE THREAD

**Issue by gedw99** [otiai10/gosseract#144]
I just tried via the demo running on heroku. It gave back the text but all as one long string 

The image was a invoice with certain data in specific name value pairs and it's those name value pairs that allow me to classify who the invoice is from.

So if I knew the position then I would've able to deduce who it was from since companies structure their invoices and receipts vary differently.

**Comment by otiai10** [comment]
ah, thanks for reporting. are you talking about github.com/otiai10/ocrserver ?
I'm gonna implement hOCR demo as well. Thanks.

**Comment by otiai10** [comment]
@gedw99 
Check it out https://ocr-example.herokuapp.com/
