### ISSUE TITLE
Whitelist and Blacklist not working with tesseract 4.0

### ISSUE THREAD

**Issue by otiai10** [otiai10/gosseract#145]
https://github.com/tesseract-ocr/tesseract/issues/751

**Comment by PuKoren** [comment]
I'm not sure if the following will help, but whitelisting seems to work well for me now (Arch Linux)

Tesseract info:
```
tesseract 4.0.0-275-g56725
 leptonica-1.77.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.1) : libpng 1.6.36 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.2
 Found AVX2
 Found AVX
 Found SSE
```

I use whitelist like this (was not aware of the SetWhitelist method when I wrote the code):
```go
gsseractClient.SetVariable("tessedit_char_whitelist", "0123456789")
```

And the text returned contains effectively only numbers. I needed to do that to improve accuracy as it reported letters before

**Comment by otiai10** [comment]
Thank you for letting me know. I will add a test runtime for tess4.0 x Arch Linux [here](https://github.com/otiai10/gosseract/tree/master/test/runtimes) 👍

**Comment by otiai10** [comment]
@PuKoren 

I added [tess4.00_lepto1.77_go1.12_ArchLinux.Dockerfile](https://github.com/otiai10/gosseract/blob/2c7b509567f94bd3627b81bff68db7ac20faca6d/test/runtimes/tess4.00_lepto1.77_go1.12_ArchLinux.Dockerfile), it seems whitelist/blacklist are not working on Tesseract4.00 as same as other runtimes.

You can try it by

```sh
docker run -it --rm gosseract/test:tess4.00_lepto1.77_go1.12_ArchLinux bash
```

See https://cloud.docker.com/repository/docker/gosseract/test for mote details.

**Comment by konkers** [comment]
Also failing under MacOS with tesseract 4.0 install via homebrew:

```> go test                       
all_test.go at line 142
        Expected to be  `He110, WorId!`
        But actual      `Hello, World!`
--- FAIL: TestClient_SetBlacklist (0.16s)
all_test.go at line 175
        Expected to be  `H    W   `
        But actual      `Hello, World!`
--- FAIL: TestClient_ConfigFilePath (0.17s)
--- FAIL: ExampleClient_SetWhitelist (0.16s)
got:
lO-100 lO-100
want:
IO- IOO 10-100
FAIL
exit status 1
FAIL    github.com/otiai10/gosseract    1.839s```

**Comment by lammel** [comment]
I used a whitelist with tesseract v4.1.1 and it was working fine.

**Comment by otiai10** [comment]
Thank you for reporting. This issue can be closed by https://github.com/otiai10/ocrserver/commit/f9ef881cb8fb1f20b0ca807af61b41a813a069d9

**Comment by otiai10** [comment]
From gosseract side, closed by https://github.com/otiai10/gosseract/releases/tag/v2.3.1
