### ISSUE TITLE
Request for info: support for uzn files

### ISSUE THREAD

**Issue by josh-atpdevel** [otiai10/gosseract#150]
I was looking into using this library hoping I could use uzn file. I have the file with the same name as my image in the same directory and using Page Seg Mode of 4. 

Does this library support the use of uzn files? if so what am I missing to get this to work?

**Comment by otiai10** [comment]
@josh-atpdevel Could you give me some example files of uzn?

**Comment by otiai10** [comment]
closing due to no response
