### ISSUE TITLE
stderr not restored properly in MacOS

### ISSUE THREAD

**Issue by raff** [otiai10/gosseract#161]
> This file is generated based on `ISSUE_TEMPLATE.md`. The issue reporter must read and remove this block before submitting.

# Summary

On MacOS (10.14) after calling NewClient (or any function that causes the low level Init function to be called) writes to stderr (i.e. log.Println) are lost.

# Reproducibility

## Reproducility Frequency

- 100%

- was working fine before I updated gosseract
- works fine if I comment out the code that redirects stderr and adds buffering

# Environment

```
uname -a

Darwin rsena-macOS 18.6.0 Darwin Kernel Version 18.6.0: Tue May  7 22:54:55 PDT 2019; root:xnu-4903.270.19.100.1~2/RELEASE_X86_64 x86_64
```

```
go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rsena/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/rsena/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p3/6z2lwcx14_l4mwl28h5n69pw0000gn/T/go-build701342837=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

```
go version

go version go1.12.5 darwin/amd64
```

```
tesseract --version

tesseract 4.0.0
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 9c : libpng 1.6.37 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.2 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found SSE
```

**Comment by otiai10** [comment]
@raff Thank you for reporting. So far, I couldn't reproduce the problem, meaning I can see messages printed on the screen (which might be stderr).

Could you give me a test case which specifies stderr is not released?

**Comment by raff** [comment]
I am using a slightly modified version (needed to be able to change the OCR Engine Mode and a few minor thing).

It looks like your version does work, but mine doesn't (and all I can think of is that have additional parameters in the Init function).

Anyway, you can close this bug.
