### ISSUE TITLE
Is there a way to retrain the tesseract model and replace it? or is it just library?

### ISSUE THREAD

**Issue by eravallirao** [otiai10/gosseract#162]
> This file is generated based on `ISSUE_TEMPLATE.md`. The issue reporter must read and remove this block before submitting.

# Summary

- bla bla bla

# Reproducibility

## Reproducility Frequency

- XX%

## Reproducible Dockerfile

```dockerfile
FROM your-os:your-version
# Describe how to reproduce your problem
# on your environment
```

Otherwise, describe how to reproduce

1. `foo bar`
2. `spam ham`
3. `hoge fuga`

# Environment

```
uname -a
```

```
go env
```

```
go version
```

```
tesseract --version
```

**Comment by otiai10** [comment]
Hi, @eravallirao

For now, `gosseract` is a library to use tesseract model and you, a user, have to train the model by using `tesseract` native API.
If you are familiar with `tesseract` C++ API to train/retrain the model and show developers how to bridge them, this can be good starting point for us to improve `gosseract`. Thanks.

**Comment by eravallirao** [comment]
Hi, **@otiai10** 

I have fine tuned(retrained) the existing model of **Tesseract** for English language(for different fonts **"eng.lstm"**). I got a **checkpoint** file. Now is there a way to integrate that model into the **gosseract**. Please help me.

**Comment by otiai10** [comment]
@eravallirao 
Could you please share what you knew and how you solved this issue?
so that I can close here.
