### ISSUE TITLE
Can't recognition russian text

### ISSUE THREAD

**Issue by DeadNumbers** [otiai10/gosseract#163]
Tesseract version 
```
tesseract 5.0.0-alpha-213-g0ac59d
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.2) : libpng 1.6.37 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.2
 Found AVX2
 Found AVX
 Found SSE
 Found libarchive 3.4.0 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.7 liblz4/1.9.1 libzstd/1.4.0
```
go env
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/Go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build037228443=/tmp/go-build -gno-record-gcc-switches"
```
go version `go version go1.12.6 linux/amd64`

uname -a 
```
Linux localhost 5.1.15-1-ck-haswell #1 SMP PREEMPT Tue Jun 25 17:43:25 EDT 2019 x86_64 GNU/Linux
```
code
```Go
func main() {
	c := gosseract.NewClient()
	defer c.Close()
	c.SetLanguage("rus")
	c.SetImage("img.jpg")
	text, err := c.Text()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(text)
}
```

This example return __always__ one result on different images.
<details>
Ва . оао р° ее щ ы чгіё“ оа Ч9 А ,‚ йО оЩИ
э и ь ч ы М КА РР ег ° 3 За ТЕ '‹_'х“"' 1"—"›";‹" 3 оЙЕО * 'а
Е. р '‚—&; од о 3 В оЛОНО ср аОН УЕ 'ЁЕ ;‚{Ё_' Ё : ы
ВЕ ЗИ ВОр ! 3 ‘ ‘ор оВАВЕ Ноко ОЕ аы АНОа :
сВ Щ аТН аЙ м АА вЕ 0. оЙЙ АВ ост ЕНЕИ а 5
МЕИ оЙ) й 1, ,73о ааоа оНЕ
ЕО е „ мй + за Т щ ы о
ВЕН \ 3 й : 133 ЕЕ -- НОЕлабе т оОООАЕ ОНО аае й
ВЕ пЕ у :: с еЩ 5132 Чра НщЕЛИ е
ЩИг ‚ дЁ у ' „аоч — оЕН
! Ь_%Ё‹ е т%:" на м, о, : Ж т ’_-.щ' .‹„Ё;!‚_: Й{;,}д‹:_ Н ‹
ОВ Р ч 3 ‹ А йЙ. › ; сблеосене о:
о ощть ч Та м о% Ща ОНО
Е ос 2 : .__Ъ_ 4 я ‚ даетиот -‹ — о ЭЩ - -Аа лн оОО ОО И Но МЫ
В Е, ла ка й ‚ №* ч ЧМЕ ло ОНа
Ма Не Н ННЕ Е - ! „и й: ЗЗЯ н НОНЕ о ятые у Мелый, - ООа
ВЕЛ оо, < ВОН пар наЕЖ- сВ ` К я о3 'Ж ЧЕ › онооаВ ас 3@&\%›3" ЗЛ - а Я : ®
е ‘ар рн СЕ ‚ < В:
Ы аНа& : оЕЙЕЕя сс ‚ о у . О 27% -` ПНИ оЕЕ . й
т Ё у : „ р” т # (° @В  БРРЕ аН Ща НН нолИ Ы, К :
‘на В оЕЛИ оо ра аЕаы ; ` 7 ! лы ИЕ Е ° й
о, я " о ой ЧЕО На
Кар ченена оаНО + м ^м - 9В ‘&*чг аВ ИО "
аТН ‘ ‚° ‘а о
вОИЩЕл ' й о - ” ец
ВОИ Н * „ ои н * ща
Вбо оЧЫ аё # › аЫ ° о
Ч й ) # . о ! —2Е Ч р Е
: Я Ь @ Е - ‚ Р вга '. — МЕИ ‚ я .
__‚щ рта и — б —
' ол ае й Х:›‘ . ь „” ОРа : . _› о НО ща 38 " Ви
сНЕ _‘ эр о У новеннц 2 ’Ё - Прсооо ОНО ь
ощ (^ —- оао , и оа Ё оааа — к ВОГ ОЛИ ва
у) 27 ПКоу ее — р ЗИ ° га й ВС
В, Эаиа , „ Па са ' л х й ка
ь с у аИЙа ® "ОЖЯ { ада ащ й@ - Е ЕНа ЭЩ т
№ ` ‘аоовы ч — " Щ оо
в ° 4 о
: : - 3° 290
й -# ‚ОЫ,
: < Кс: ЭЕНО
: $е е "7'1‚"’:_@:‚_;:‚ а
- ‚ ЗОа ЧАЕ ОО оОЙ
! УРЕН Ие -Ё'_
Ь _ ч ; пре й х _›.п„“‘›
лильь. Ч, РО НОО ОООа
56 : оОО ОГЕа
: з а* аоа
% ь ооа 2 ЗН ОЕ
оя 39® оъ ча % * 3 7° оу ОНИ
рч ы В, , 99 й В .; н Е = ЁЪ…Ё
„ Р 3 С В одщае, % ‘ х х
: ‚ @ ы Ва ае и Ь
р й вг Е К х : и 2 # ъ Ч м с› анеся
у — Е ; ч оАЫ
л : В 3* ;_"_:.‘і‚
О '. ! # о@ е л % ” '‹_›."-:‘"" НУ
Р 3 " Ч \ е
; Р ; о нна ай
„ё оы . :
у й ) „ ар т
‚ — ай, ы ®е ., Р ‘Ча т ащ айЕ ›
г ба 4 3 я @ ® ж›\щ; 3
е шы ##
а
\ * у ВАЬ
— уабелЕ , 3 .',“Ё"›‘Т‘ о й оао АщЕ На ` т М
р ооа сс ПЫНЕ ааЕ СЕВ а — ;
Ё 8 л оК В РОЫ \ 8 + ОЫ .
„58 - 5У ” * 0Й $ ы
: еа К В ка аоа : ы
р о ‘
Н ооа ! еа 5 ‚ - ТОЩНЗОЛЫ й "
-5 В. СО .. ЯН В : Эа
ол : ° Са В В ° Аа о Ч
‹ х а98 В ‘р ‘24 ь 3 ИЕ ‹ ТРОНЫ ОАа ана -
‘, СоащЙ В оао - оо ааЫ оы н - ‹О ы
—а оаа ао ол то А.)оо| НЕ 3 то: › оо оо ОАУЕ рн
* НеЫщЙ РОИ оЕ лк) оаЫ и С Вг у * о! аЗОИ тащ Заа
ВО аЕ :д’ о оРОИ Ё е Ё : МЕН о, * оа « анаа С
В, ^ я 7 Рло о6 ОСН В ; ы Р аЕАр аее росуо о ООа ооа
ое ‘РОЩДя П, В я оНОЙ ое аа
1 ы орт сс —- ЭВЫ Еа те л н
! —тСВа е ласт ао оо ОДаЙ Ц Е ЛОНО ОВ АНр ОЕ Заа ОЕ ОЕ с ооая
: 7 НаЙ оо о6 Р й Р 3 оа) ОДОеИНЕеНС о о ОНААСЦ О - — УНЪЗЬИ Ь о, т ь
: 17 ЦАВ ау осс ст оОНЕ 8 ; ‘ О ЕЬ АВ ао ИИ — лВ о°
311 пураННИЫ . мЫИЫ Ч ОА ре от З ай соо НЙ ы
В иа рщ й, ооа оТа 4 Н -ло ау О ща : —0а ИЁ
СОАа 3 ВЕВа ло аЬ НнЫ КО Е
сАеЩЫ ощ о ааЕа О. \5я 3 аао . САЕ
В : 3 © й НУ Ё%’и ЕО ООЕ —- бос ЕНЕ
сРОНА аеа 3 Е ПИа аста К — обо оОНО
@ П, У оо оча к Ы Ч К лВО
о В оООО ой О ‹° ВН а ер аеа, „ЕО оаа
т о $ й ' В ,
(& овЕ о * 2 —ай а
: НЕНЕ т` Н 2° аВМ с <
с ЗАМ, - лщ
оо Г М ом, =' Г, ДОДИРОНИИ
</details>

But tesseract from cli finded some text on this image

`$ tesseract vS_1BDkq_Us.jpg out -l rus`

<details>
ю П ССИЙСКАЯ ФЕДЕРАЦИЯ

ОТДЕЛОМ ВНУТРЕННИХ ДЕЛ

 

    
 

ОКТЯБРЬСКОГО ОКРУГА ° т
ГОРОДА АРХАНГЕЛЬСКА
<
ы …1’7. 12.2004 ) 292-000 *
—
[=>]
<
К
—
<

 

%‚ ..

чча ноллись

   
 

ооы Ч овЕ ьва ае

е ЕВЕ ЕЕЕЕЕЕЕНЕНЕНО

 

л ВДОСКУПЬЯН
ПРОРАБ -
.
ПЕТРОВИЧ

окнество

. ОН 12.09.1682

реждения.

мст - ГОР. АРХАНГЕЛЬСК

рождения

 

000000 %0

 

</details>

Picture for test 
![vS_1BDkq_Us](https://user-images.githubusercontent.com/9416005/60512668-d9f61780-9cdd-11e9-8e85-e433ad15d70b.jpg)

**Comment by DeadNumbers** [comment]
Also, do not worry, it is a fake passport.

**Comment by otiai10** [comment]
@otiai10 
https://github.com/tesseract-ocr/tessdata_best/blob/master/rus.traineddata

**Comment by otiai10** [comment]
@otiai10 

# Pros

```
% tesseract rus.jpg stdout -l rus
Detected 32 diacritics
В ОСсСиИЙСКАЯ ФЕДЕРАЦИЯ

ОТДЕЛОМ ВНУТРЕННИХ ДЕЛ








ОКТЯБРЬСКОГО ОКРУГА а
ГОРОДА АРХАНГЕЛЬСКА
=
нема 17.12.2004, 292-000 ®
5
=
3 , я =
й =
=
=
ЕЕ олие
: 2 ЕЕ Е ВЕ ВЕ Бе БЕ Вы О кайт
нев шес НЕ НееЕ
м ВДОСКУПЬЯН
мя ПРОРАБ =
к
ны ПЕТРОВИЧ
=
„МУЖ. мк, 12.09.1682 ©
мт, ГОР. АРХАНГЕЛЬСК =
=
=
[=]
=
=




```

# Cons

```
% go run main.go
№ О ССИЙСКАЯ ФЕДЕРАЦИЯ
енору база ОТДЕЛОМ ВНУТРЕННИХ ДЕЛ
ОКТЯБРЬСКОГО ОКРУГА к
ГОРОДА АРХАНГЕЛЬСКА
К)
Дет „17.12.2004 Кода ао 292—000 =
оо, °
В Зуоф ПИ о
НЕО ао =
5 фа т & 1 ‘Личный кол.
ОКНО 3ы/Х Е =
ЗА Во топки =
Чееоао разн *
ж Рене РТ РОРСЕ ВОР орорещернефнейннын—
НН РННЕНННЕНеННННННЕВН
И щи ВДОСКУПЬЯН
са
<?
‹3е@ ПРОРАБ -
8 у в. =
= № ея ПЕТРОВИЧ
— <396 р, =
“2 „МУЖ. м, 12.09.1682 =
5 ю \есто|
3 “т, ГОР. АРХАНГЕЛЬСК °
& =
=
| ©
=
Е " (=>)
А оков ни еее овец а Д
```

# Env

```
tesseract 4.0.0
 leptonica-1.77.0
  libgif 5.1.4 : libjpeg 9c : libpng 1.6.37 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.2 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found SSE
```

```
go version go1.12 darwin/amd64
```

**Comment by otiai10** [comment]
@DeadNumbers 
Let me confirm one thing

> This example return always one result on different images.

Does it mean you get **the same result** with **several different images**?

**Comment by otiai10** [comment]
without any reply in a week, this issue will be closed

**Comment by otiai10** [comment]
Gosseract can be effective if you know the position of chars and fonts and you can trim the original image only with those chars. Not sure this comment helps your problem but it seems you are no longer interested in this issue. Gonna be closed. Thx
