### ISSUE TITLE
info in pixReadStreamPng: converting (cmap + alpha) ==> RGBA

### ISSUE THREAD

**Issue by yiyiyaya** [otiai10/gosseract#176]
```
       client := gosseract.NewClient()
        defer client.Close()
        client.SetImage("./1.jpg")
        text, err := client.Text()
        if err != nil{
        fmt.Println("----------------------------------err", err)
        }
        fmt.Println(text)
        fmt.Println("--------------------------------------------------text", text)
```
output : info in pixReadStreamPng: converting (cmap + alpha) ==> RGBA
             Info in pixReadStreamPng: converting 8 bpp cmap with alpha ==> RGBA

**Comment by yiyiyaya** [comment]
resolved

**Comment by otiai10** [comment]
how?

**Comment by otiai10** [comment]
@yiyiyaya how?

**Comment by otiai10** [comment]
@yiyiyaya In OSS project, it's very important to share knowledge and prevent someone else from doing the same shit. Please share what you did and how you did solve it.
