### ISSUE TITLE
Running gosseract prevents logs from printing

### ISSUE THREAD

**Issue by sukshifr** [otiai10/gosseract#177]
> Logs are not printing when using gosseract in my project. After initiating gosseract client iam not seeing any log.println's. Below is my code

```
fmt.Println("Configuring OCR Client")
	totalClients, err := strconv.ParseInt(opts.OcrClients, 10, 64)
	fmt.Println("Total OCR Clients: ", int(totalClients))

	var ocrClients []*gosseract.GClient

	log.Println("hello")
	ocrClients = gosseract.NewClient(int(totalClients))
	log.Println("hello1")
	fmt.Println("Done!")

```
Below are my logs

```
Configuring OCR Client
Total OCR Clients:  60
hello
Done!
```

hello1 is not printed. 
Please can you help me resolve the issue?

**Comment by otiai10** [comment]
@sukshifr can you give me a reproducible Docker? and please follow the issue template

**Comment by otiai10** [comment]
No reaction for a while
