### ISSUE TITLE
Leaks /dev/ttysXXX file handles even when Close() is manually called

### ISSUE THREAD

**Issue by tebruno99** [otiai10/gosseract#178]
# Summary
This is a real issue for me as I am capturing images via security camera and every frame runs through Tesseract in real time.

While running in a loop over files, OpenCV video frame, or as a web service, gosseract is opening a new /dev/ttys002 (or /dev/pts/004) every time an image is parsed. This eventually leads to a situation of running out of allowed file handlers.

I have attached the example Go projects that have the issue and a C++ version that does not.

<img width="1282" alt="lsof screenshot" src="https://user-images.githubusercontent.com/24335/68998029-9823d300-0872-11ea-9e30-20dd6f6b80d8.png">

# Reproducibility
Always

# Environment
macOS 10.14, Tesseract 4.1.0
Ubuntu 19.01, Tesseract 4.0

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tbruno/Library/Caches/go-build"
GOENV="/Users/tbruno/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tbruno/Projects/GolandProjects/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2r/vy9wb4w90snd6wwv06ts6rth0000gn/T/go-build449183315=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

```
go version go1.13.4 darwin/amd64
```

```
tesseract 4.1.0
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 9c : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 1.0.3 : libopenjp2 2.3.1
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found SSE
```

**Examples** (I'm using the same jpg file, but this happens even if a new file is opened and also happens with SetImageFromBytes)

```
func main() {
	client := gosseract.NewClient()
	for {
		client.SetImage("/Users/tbruno/test.jpg")
		text, _ := client.Text()
		fmt.Println(text)
	}
	client.Close()
}
```
```
func main() {
	for {
		client := gosseract.NewClient()
		client.SetImage("/Users/tbruno/test.jpg")
		text, _ := client.Text()
		fmt.Println(text)
		client.Close()
	}
}
```
[TessTester-ClientInLoopGo.zip](https://github.com/otiai10/gosseract/files/3854602/TessTester-ClientInLoopGo.zip)
[TessTester-SingleClientGo.zip](https://github.com/otiai10/gosseract/files/3854603/TessTester-SingleClientGo.zip)
[TessApi-NoLeakCpp.zip](https://github.com/otiai10/gosseract/files/3854604/TessApi-NoLeakCpp.zip)

**Comment by tebruno99** [comment]
I am still learning about cgo but I was able to stop this from happening by removing the stderr stuff from tessbridge.cpp Init

```
    // {{{ Redirect STDERR to given buffer
    fflush(stderr);
    int original_stderr;
    original_stderr = dup(STDERR_FILENO);
    (void)freopen("/dev/null", "a", stderr);
    setbuf(stderr, errbuf);
    // }}}
```

**Comment by otiai10** [comment]
aaaaaaaahhhhhhhhh, likely... Thank you for your information, very helpful.

**Comment by craziex** [comment]
@otiai10  can fix it ?  i get that error too, run out of  File descriptors limit in some time.

**Comment by otiai10** [comment]
gonna fix it in a week, if I can have time

**Comment by craziex** [comment]
@otiai10 thanks for your reply.

**Comment by craziex** [comment]
@otiai10 when to fix this bug？

**Comment by vlad-s** [comment]
Can also confirm this happening on Pop!_OS 19.10, a Debian 10 VM, and three different Centos 7 machines. I am using this in a web server based application, and this bug is making `gosseract` be useless in long lived applications. We can test this by using a simple Go program, checking the file descriptors, and then using the code @tebruno99 used, or any other variation. I for one encountered it using gosseract by loading an image from bytes.

```go
package main

import "time"

func main() {
	time.Sleep(10 * time.Second)
}
```
```sh
$  go build -o leak && ./leak & ; ls -l /proc/`pgrep leak`/fd | wc -l
[1] 18999
4
```

Afterwards we load a number `N` of images to test the theory that for every image OCR'd, it leaks a file descriptor.
```go
package main

import (
	"fmt"

	"github.com/otiai10/gosseract"
)

func main() {
	blocker := make(chan int, 1)
	client := gosseract.NewClient()
	for i := 0; i < 10; i++ {
		client.SetImage("./001-helloworld.png")
		fmt.Println(client.Text())
	}
	client.Close()
	<-blocker
}
```
```sh
$ go build -o leak && ./leak
$ ls -l /proc/`pgrep leak`/fd
total 0
lrwx------ 1 vlad vlad 64 Dec 15 20:28 0 -> /dev/pts/0
lrwx------ 1 vlad vlad 64 Dec 15 20:28 1 -> /dev/pts/0
lrwx------ 1 vlad vlad 64 Dec 15 20:28 10 -> /dev/pts/0
lrwx------ 1 vlad vlad 64 Dec 15 20:28 11 -> /dev/pts/0
lrwx------ 1 vlad vlad 64 Dec 15 20:28 12 -> /dev/pts/0
lrwx------ 1 vlad vlad 64 Dec 15 20:28 2 -> /dev/pts/0
lrwx------ 1 vlad vlad 64 Dec 15 20:28 3 -> /dev/pts/0
lrwx------ 1 vlad vlad 64 Dec 15 20:28 4 -> /dev/pts/0
lrwx------ 1 vlad vlad 64 Dec 15 20:28 5 -> /dev/pts/0
lrwx------ 1 vlad vlad 64 Dec 15 20:28 6 -> /dev/pts/0
lrwx------ 1 vlad vlad 64 Dec 15 20:28 7 -> /dev/pts/0
lrwx------ 1 vlad vlad 64 Dec 15 20:28 8 -> /dev/pts/0
lrwx------ 1 vlad vlad 64 Dec 15 20:28 9 -> /dev/pts/0
$ ls -l /proc/`pgrep leak`/fd | wc -l
14
```

We can test this with any number. I had to resort to using `exec.Command("tesseract", args...)` in our service otherwise the API was useless once it hit the systemd limit of 1024 open files.

**Comment by tebruno99** [comment]
Thanks!!

**Comment by otiai10** [comment]
Guys, please check the latest version and reopen this issue if you still find anything wrong

**Comment by otiai10** [comment]
Thank you for being patient
