### ISSUE TITLE
tessbridge.cpp:5:10: fatal error: leptonica/allheaders.h: No such file or directory

### ISSUE THREAD

**Issue by QQ3544291** [otiai10/gosseract#182]
# Summary

Installation failed on win 10 x64 by go get -t github.com/otiai10/gosseract
$ go get -t github.com/otiai10/gosseract
# github.com/otiai10/gosseract
tessbridge.cpp:5:10: fatal error: leptonica/allheaders.h: No such file or directory
 #include <leptonica/allheaders.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

I don't know about header files,. How do I install them on windows?
leptonica/allheaders.h This is header files?
# Reproducibility

## Reproducibility Frequency

- 100%

## Reproducible Dockerfile

```dockerfile
FROM your-os:your-version
# Describe how to reproduce your problem
# on your environment
```

Otherwise, describe how to reproduce

Install GO lan
Install GCC (64 Bit Compiler)
Install GIT
Install Tesseract from this site
https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-setup-3.05.02-20180621.exe
go get -t github.com/otiai10/gosseract

# Environment

```

```

```
go env
```
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\VULCAN\AppData\Local\go-build
set GOENV=C:\Users\VULCAN\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Go\go\bin
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\VULCAN\AppData\Local\Temp\go-build610875910=/tmp/go-build -gno-record-gcc-switches
```
go version
```
$ go version
go version go1.13.5 windows/amd64
```
tesseract --version
```$ tesseract --version
tesseract 3.05.02
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.2.0

**Comment by otiai10** [comment]
leptonica-dev?

**Comment by QQ3544291** [comment]
oh,I don't know how how to install it.The reason is that My Google search for the installation method is linux, but I'm just getting started.I hope you can tell me how to install it on Windows.
(╥╯^╰╥)

> leptonica-dev?

**Comment by QQ3544291** [comment]
I don't know if cygwin will help me install this leptonica.
I'll try.
ε=(´ο｀*)))
I'm sorry for the trouble

**Comment by otiai10** [comment]
https://vorba.ch/2014/tesseract-cygwin.html
seems helpful

**Comment by otiai10** [comment]
don't close this issue and please share any knowledge here you found / would find

**Comment by otiai10** [comment]
@QQ3544291 Have you solved this issue or no longer need it?

**Comment by QQ3544291** [comment]
I'm sorry. I seem to be busy with the middle school exam now. Now I also have new problems, as shown in the figure
[https://github.com/QQ3544291/error/blob/master/error.png](url)

**Comment by otiai10** [comment]
OK, it seems another problem, NOT represented by this issue thread. I'm gonna close here.

Good luck with your exam ;)

**Comment by HelloHaiGG** [comment]
hello, on my Linux (debian) "go get github.com/otiai10/gosseract" encountered the same error message, but I don't know how to install the missing libraries on Linux, please help me!!!!!!!!!!!!

**Comment by otiai10** [comment]
@HelloHaiGG 
Is there the runtime you are working on in this folder?
https://github.com/otiai10/gosseract/tree/master/test/runtimes
