### ISSUE TITLE
fatal error: leptonica/allheaders.h: No such file or directory

### ISSUE THREAD

**Issue by ayaya118** [otiai10/gosseract#186]
# github.com/otiai10/gosseract
tessbridge.cpp:5:10: fatal error: leptonica/allheaders.h: No such file or directory
 #include <leptonica/allheaders.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

![1](https://user-images.githubusercontent.com/4150721/72307330-e3acfe80-36b4-11ea-872a-9ba4657fe9a5.png)

how can fix it ?

**Comment by otiai10** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/Compiling#windows

**Comment by KyllianHmd** [comment]
<img width="691" alt="Capture d’écran 2020-01-15 à 16 07 37" src="https://user-images.githubusercontent.com/27286901/72449811-2eac3c00-37b1-11ea-98c2-35cae075a457.png">

I'm on macOS and I followed this part : https://github.com/tesseract-ocr/tesseract/wiki/Compiling#macos, but still have the same error, any idea ?

**Comment by ayaya118** [comment]
yes.thx!

**Comment by otiai10** [comment]
@ayaya118 
does it work?

**Comment by ayaya118** [comment]
yes,it`s fine!

**Comment by otiai10** [comment]
cool. I might ask details when any similar issues are reported. thx anyway

**Comment by kvnxiao** [comment]
How exactly do you fix this issue @ayaya118 ?

Did you follow `Build the latest library` or `Develop Tesseract` instructions on the https://tesseract-ocr.github.io/tessdoc/Compiling#Windows page?
