### ISSUE TITLE
Benchmark improvements on GetBoundinxBoxes functions

### ISSUE THREAD

**Issue by leftwichj** [otiai10/gosseract#187]
#Summary

In looking at the library noticed room for small improvements on the GetBoundingBoxes and GetBoundingBoxesVerbose actions.

Within those methods setting the capacity of the returned array will reduce allocs/op and B/op
out = make([]BoundingBox, 0, length)

I can do a quick PR on this if you would like.

**Comment by otiai10** [comment]
Merged. Thanks a lot!

**Comment by leftwichj** [comment]
Thank you.  Great library.
