### ISSUE TITLE
exec: "gcc": executable file not found in $PATH

### ISSUE THREAD

**Issue by sushiljacksparrow** [otiai10/gosseract#190]
> This text is generated based on `ISSUE_TEMPLATE.md`. The issue reporter must read and remove this block before submitting.

# Summary

Creating docker image fails with error - 
exec: "gcc": executable file not found in $PATH

# Reproducibility
Yes
## Reproducibility Frequency

-100%

## Reproducible Dockerfile

```dockerfile
FROM golang:1.13-alpine
EXPOSE 8080

WORKDIR $GOPATH/src/github.com/go-ocr
COPY go.mod ./
RUN go mod download
RUN mkdir -p $GOPATH/src/github.com/go-ocr
COPY . $GOPATH/src/github.com/go-ocr


RUN go build -o ocr .

CMD ["/go/src/github.com/go-ocr/ocr"]


# Describe how to reproduce your problem
# on your environment
docker build -t ocr .

Otherwise, describe how to reproduce


# Environment

```
uname -a
```
Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64
```
go env
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sushils/Library/Caches/go-build"
GOENV="/Users/sushils/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/sushils/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/sushils/go/src/github.com/go-ocr/go.mod"
CGO_CFLAGS="-I/usr/local/opt/leptonica/include -I/usr/local/opt/tesseract/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/usr/local/opt/leptonica/lib -L/usr/local/opt/tesseract/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1l/q2v3vngj6gl5psfjw4cd3mxc6fwbcg/T/go-build080103148=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
go version
```
go version go1.13.5 darwin/amd64
```
tesseract --version
```
tesseract 4.1.1
 leptonica-1.79.0
  libgif 5.2.1 : libjpeg 9d : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 1.1.0 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found FMA
 Found SSE

**Comment by otiai10** [comment]
Just because you don't have `gcc`, do you?

BTW, your Dockerfile is NOT reproducible, since I don't have your `go.mod`, either `.`.

**Comment by sushiljacksparrow** [comment]
### $ gcc --version

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

* here is my go.mod

module github.com/go-ocr

go 1.13

require (
	github.com/gin-gonic/gin v1.5.0
	github.com/otiai10/gosseract v2.2.1+incompatible
)

**Comment by otiai10** [comment]
1. Your gcc is existing on **YOUR MACHINE**, not on your container.
2. I still don't have your application code: represented by `.`.

You can try this line on your dockerfile to install `gcc` on your container.

```dockerfile
RUN apk add build-base
```

Please don't forget to report any progress on this issue thread, so that other developers can check and learn for similar problems.

**Comment by sushiljacksparrow** [comment]
Ok, now I am hitting a separate problem 

# github.com/otiai10/gosseract
tessbridge.cpp:5:10: fatal error: tesseract/baseapi.h: No such file or directory
 #include <tesseract/baseapi.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.


Here is my latest Dockerfile

FROM golang:1.13-alpine
EXPOSE 8080

WORKDIR $GOPATH/src/github.com/go-ocr
COPY go.mod ./
RUN mkdir -p $GOPATH/src/github.com/go-ocr

RUN go mod download

RUN apk add build-base
COPY . $GOPATH/src/github.com/go-ocr


RUN go build -o ocr .

CMD ["/go/src/github.com/go-ocr/ocr"]

**Comment by otiai10** [comment]
See alpine installation instruction here
https://github.com/otiai10/gosseract/blob/master/test/runtimes/alpine.Dockerfile

**Comment by sushiljacksparrow** [comment]
It finally worked.

Thanks for your support and direction. Here is my latest docker file

FROM golang:1.13-alpine


RUN apk update
RUN apk add \
  g++ \
  git \
  musl-dev \
  go \
  tesseract-ocr-dev

WORKDIR $GOPATH/src/github.com/go-ocr
COPY go.mod ./
RUN mkdir -p $GOPATH/src/github.com/go-ocr

RUN apk add build-base
COPY . $GOPATH/src/github.com/go-ocr


RUN go build -o ocr .
EXPOSE 8080

CMD ["/go/src/github.com/go-ocr/ocr"]
