### ISSUE TITLE
Is this support Tesseract 4.0x ?

### ISSUE THREAD

**Issue by lleiiell** [otiai10/gosseract#193]
# have some bad case, one is: 

img: 
![image](https://user-images.githubusercontent.com/2200592/77316640-c0ea3680-6d44-11ea-807e-7d8770bb07d8.png)

url: https://static2.ivwen.com/users/16720809/832840a829c44141a1687f141872a75e.jpeg

```go
	client := gosseract.NewClient()
	defer client.Close()

	client.SetLanguage("chi_sim")
	client.SetImage("/Users/lanjingren/Desktop/ocr/badcase/WX20200323-190047@2x.png")
```

Result: 

![image](https://user-images.githubusercontent.com/2200592/77316604-add76680-6d44-11ea-8ce0-12e67342ea57.png)

Expected: empty 

# Environment

```
go version go1.13 darwin/amd64
```

```
tesseract --version

tesseract 4.0.0
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 9c : libpng 1.6.37 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.2 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found SSE
```

**Comment by otiai10** [comment]
It supports 4.0, but this is an issue for followings:

1. There are some implicit options which tesseract CLI uses
2. If you use `gosseract`, better to know the source image and trim it properly to get expected result.

**Comment by lleiiell** [comment]
> It supports 4.0, but this is an issue for followings:
> 
> 1. There are some implicit options which tesseract CLI uses
> 2. If you use `gosseract`, better to know the source image and trim it properly to get expected result.

Thanks. I used the direct tesseract cli command, and got expected result. not sure how to trim images since images are from user upload

```
tesseract example.jpg out -l chi_sim
```

**Comment by otiai10** [comment]
To answer your original question described in the title, yes, it does support 4.x
