### ISSUE TITLE
failed to initialize TessBaseAPI

### ISSUE THREAD

**Issue by Cedric-Caballol-Shepy** [otiai10/gosseract#194]
Hi, thanks for this lib.

# Summary

I can't use gosseract due this error `failed to initialize TessBaseAPI`. How can I get rid of it ?

# Reproducibility

I used this function to test (fastly) gosseract :
```
func getHocrFromImage() (err error) {
	client := gosseract.NewClient()
	defer client.Close()
	err = client.SetImage("../test-docs/file02.tif")
	if err != nil {
		return fmt.Errorf("err setImage : %s", err.Error())
	}
	var hocr string
	hocr, err = client.HOCRText()
	fmt.Println("hocr : ", hocr)
	return fmt.Errorf("HOCRText : %s", err.Error())
}
```

With this test function (generated by Visual Studio Code)
```
func Test_getHocrFromImage(t *testing.T) {
	tests := []struct {
		name    string
		wantErr bool
	}{
		{
			name:    "OK",
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if err := getHocrFromImage(); (err != nil) != tt.wantErr {
				t.Errorf("getHocrFromImage() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}
```

The output is : 
```
hocr :  
--- FAIL: Test_getHocrFromImage (0.01s)
    --- FAIL: Test_getHocrFromImage/OK (0.01s)
        c:\Users\ccaballol\Documents\go\src\eve\ocr-v2\processor\tesseract_test.go:18: getHocrFromImage() error = HOCRText : failed to initialize TessBaseAPI with code -1: , wantErr false
FAIL
FAIL	eve/ocr-v2/processor	0.071s
FAIL
Error: Tests failed.
```

# Environment

### Os : Windows 10

```
> go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ccaballol\AppData\Local\go-build
set GOENV=C:\Users\ccaballol\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\ccaballol\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\CCABAL~1\AppData\Local\Temp\go-build125718318=/tmp/go-build -gno-record-gcc-switches
```

```
> go version
go version go1.13.4 windows/amd64
```

```
> tesseract --version
tesseract 4.1.1
 leptonica-1.79.0
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 2.0.4) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 1.1.0 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.4.2 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.4
```

I've used the MSYS2 installation guide to install Tesseract. I've tested my installation by using it in command-line with a sample image and it works well. 

Thanks in advance for your help.

**Comment by otiai10** [comment]
Can you call `gosseract.Version()` tho?

**Comment by Cedric-Caballol-Shepy** [comment]
`gosseract.Version()` gives `4.1.1`.

**Comment by Cedric-Caballol-Shepy** [comment]
I don't know if it can help but I have another information (I didn't think about that before) :
When I've installed Tesseract I've chosen to install only the french language. 
I've changed my code consequenlty (added `client.SetLanguage("fra")`) but I'm still getting the same error.

**Comment by veryWrong** [comment]
> I don't know if it can help but I have another information (I didn't think about that before) :
> When I've installed Tesseract I've chosen to install only the french language.
> I've changed my code consequenlty (added `client.SetLanguage("fra")`) but I'm still getting the same error.

Maybe you didn't set the environment variable `TESSDATA_PREFIX`
Try it in init:
```
os.Setenv("TESSDATA_PREFIX", "The path of testdata")
```

**Comment by veryWrong** [comment]
@Cedric-Caballol-Shepy 
I seem to have encountered this error.
Maybe you didn't set the environment variable TESSDATA_PREFIX
Try it in init:

os.Setenv("TESSDATA_PREFIX", "The path of testdata")

**Comment by Cedric-Caballol-Shepy** [comment]
It works with `os.Setenv("TESSDATA_PREFIX", "The path of tessdata")` !
That's weird because I have it set on Windows (if I do echo %TESSDATA_PREFIX% it gives me the path).

Thank you !
