### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by jairforero** [otiai10/gosseract#197]
tessbridge.cpp:5:10: fatal error: leptonica/allheaders.h: No such file or directory

**Comment by otiai10** [comment]
Install leptonica / leptonica-dev / something similar

**Comment by MoonS11** [comment]
Is it possible to compile lep or lep-dev into the minggw environment on windows?

**Comment by otiai10** [comment]
https://github.com/otiai10/gosseract/blob/main/test/runtimes/mingw.Dockerfile
