### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by damiandominella** [otiai10/gosseract#198]
# Summary

There's a problem with this package, when working with a medium-large number of files (> 120). I use Tesseractt to process some PDF files and by listing the opened files by the application during the process (`lsof -p PID_OF_APP | wc -l`) I can see that the amount is always growing until it reaches the default limit (1024). By listing the files I can see that they are all CHR files (special characters files) opened and used by Tesseract. 

# Environment

Ubuntu 20.04 LTS

```
tesseract --version
4.1.1
```

**Comment by otiai10** [comment]
which version of gosseract are you using

**Comment by otiai10** [comment]
no reply
