### ISSUE TITLE
Unable to run tesseract in Go

### ISSUE THREAD

**Issue by anandabhaumik** [otiai10/gosseract#203]
> This text is generated based on `ISSUE_TEMPLATE.md`. The issue reporter must read and remove this block before submitting.

# Summary

- Unable to run Sample file using otiai10/gosseract" in Windows10

tessbridge.cpp:5:10: fatal error: leptonica/allheaders.h: No such file or directory
    5 | #include <leptonica/allheaders.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

# Reproducibility
Yes

## Reproducibility Frequency

- Always

## Reproducible Dockerfile

```dockerfile
FROM your-os:your-version
Windows 10
# Describe how to reproduce your problem
# on your environment
```
Windows 10-> Visual Studion -> 
Otherwise, describe how to reproduce
package main

import (
	"fmt"

	"github.com/otiai10/gosseract"
)

func main() {

	fmt.Println("Sample Test")

	client := gosseract.NewClient()

	defer client.Close()
	client.SetImage("example01.png")
	client.SetLanguage("eng")

	output, err := client.Text()
	if err != nil {
		panic("Failed to extract the text")
	} else {
		fmt.Println(output)
	}

}# Environment

```
uname -a
```

```
go env
```

```
go version
```

```
tesseract --version :

$ tesseract -v
tesseract v4.0.0.20190314
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.2.0
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found SSE 
```

**Comment by otiai10** [comment]
dup https://github.com/otiai10/gosseract/issues/132
