### ISSUE TITLE
xref Prev does not point to xref ?

### ISSUE THREAD

**Issue by shumintao** [otiai10/gosseract#206]
panic: malformed PDF: xref Prev does not point to xref

goroutine 1 [running]:
main.main()
        /Users/facebook/go/src/gitee.com/pdf2txt/main.go:12 +0xbd

**Comment by otiai10** [comment]
I'm not sure how you are using gosseract in your Go project, googled the error, found this block,

https://github.com/rsc/pdf/blob/c47d69cf462f804ff58ca63c61a8fb2aed76587e/read.go#L366-L368

```go
		if tok != keyword("xref") {
			return nil, objptr{}, nil, fmt.Errorf("malformed PDF: xref Prev does not point to xref")
		}
```

and I guess your PDF is just malformed.
