### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by thzll** [otiai10/gosseract#212]
> This text is generated based on `ISSUE_TEMPLATE.md`. The issue reporter must read and remove this block before submitting.

# Summary

- bla bla bla

# Reproducibility

## Reproducibility Frequency

- XX%

## Reproducible Dockerfile

```dockerfile
FROM your-os:your-version
# Describe how to reproduce your problem
# on your environment
```

Otherwise, describe how to reproduce
package main

import (
"fmt"
"github.com/otiai10/gosseract/v2"
)

func main() {
	client := gosseract.NewClient()
	defer client.Close()
	client.SetImage("path/to/image.png")
	text, _ := client.Text()
	fmt.Println(text)
	// Hello, World!
}
test$ GOOS=linux CGO_ENABLED=1 GOARCH=amd64 go build main.go 
# runtime/cgo
linux_syscall.c:67:13: error: implicit declaration of function 'setresgid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
linux_syscall.c:67:13: note: did you mean 'setregid'?
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/unistd.h:593:6: note: 'setregid' declared here
linux_syscall.c:73:13: error: implicit declaration of function 'setresuid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
linux_syscall.c:73:13: note: did you mean 'setreuid'?
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/unistd.h:595:6: note: 'setreuid' declared here

# Environment

```
os MacOsx Catalina
```

```
go env
```

```
go version
```
1.62
```
tesseract --version
```

**Comment by otiai10** [comment]
Please read and follow the issue template, please.
