### ISSUE TITLE
can't install go get -t github.com/otiai10/gosseract

### ISSUE THREAD

**Issue by tmb-piXel** [otiai10/gosseract#214]
# Summary

go get -t github.com/otiai10/gosseract
tessbridge.cpp: In function ‘int Init(TessBaseAPI, char*, char*, char*, char*)’:
tessbridge.cpp:46:10: warning: ignoring return value of ‘FILE* freopen(const char*, const char*, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
   46 |   freopen("/dev/null", "a", stderr);
      |   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
tessbridge.cpp:60:10: warning: ignoring return value of ‘FILE* freopen(const char*, const char*, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
   60 |   freopen("/dev/null", "a", stderr);
      |   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~

linux version
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
```

```
go env
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pixel/.cache/go-build"
GOENV="/home/pixel/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pixel/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/pixel/projects/instagramStoriesBot/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build885083553=/tmp/go-build -gno-record-gcc-switches"
```
go version
```
go1.13.8 linux/amd64
```
tesseract --version
```
tesseract 4.1.1
 leptonica-1.79.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.3) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.1
 Found AVX
 Found SSE
 Found libarchive 3.4.0 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.4

**Comment by tmb-piXel** [comment]
Shows a warning, but everything works, you can close issue

**Comment by otiai10** [comment]
Thank you for your checking :+1:
