### ISSUE TITLE
Cleaning/Removing extra characters

### ISSUE THREAD

**Issue by hajsf** [otiai10/gosseract#218]
trying to reproducethe sample provided (without docker), as below:
```go
package main

import (
	"fmt"
	"github.com/otiai10/gosseract/v2"
)

func main() {
	client := gosseract.NewClient()
	defer client.Close()
	client.SetImage("./x.png")
	text, e := client.Text()
	fmt.Println(e)
	fmt.Println(text)
}
```
But got te below error:
```bash
PixImage is not set, use SetImage or SetImageFromBytes before Text or HOCRText
```
![image](https://user-images.githubusercontent.com/46838626/118513944-cc64a200-b73c-11eb-9fab-6b564b5c30b2.png)

Note:
I got [tesseract](https://github.com/tesseract-ocr/tesseract) installed qt my WSL (Ubuntu under Win 10) as:
```bash
$ sudo apt-get update -qq
$ sudo apt-get install -y -qq libtesseract-dev libleptonica-dev
$ sudo apt-get install -y -qq libtesseract-dev tesseract-ocr
$ sudo sudo apt-get install -y tesseract-ocr-eng tesseract-ocr-ara
```
And added `gosseract` as:
```bash
$ go get -u -v github.com/otiai10/gosseract/v2
```
What wrong thig I'm doing here?

**Comment by hajsf** [comment]
Sorry, The image extension was wrong, in the code it is `png` while in real it is `jpg` I fixed it and for the below imge:

![x](https://user-images.githubusercontent.com/46838626/118516279-d7b8cd00-b73e-11eb-9667-2ec3046c5dc6.jpg)

I got the below output text:

```bash
hajsf@AIS-DM-YOUSEF-L:/mnt/d/wsl$ go run hasan.cv
<nil>
“a , =. Maybe we should all just listen to
fa f wl A A
Pa ; Soe records and quit our jobs
eal t
as di E ed
oa sf .
ad i. ik a
j e S — AZ QUOTES
```
1. How can I clean the extra characters?
2. Why the name `Jack while`  was not read?

**Comment by otiai10** [comment]
Can you change the title of issue to represent your problem correctly?

**Comment by gozelus** [comment]
same problem, need help.

**Comment by otiai10** [comment]
If you know the coords of texts, trim your images on your application first.
