### ISSUE TITLE
Can't find tesseract v4.1.1 Dockerfile?

### ISSUE THREAD

**Issue by Xuzan9396** [otiai10/gosseract#221]
Whitelist and Blacklist not working with tesseract 4.0

**Comment by otiai10** [comment]
#145

**Comment by Xuzan9396** [comment]
https://github.com/otiai10/gosseract/releases/tag/v2.3.1
 
 Dockerfile is 4.0.0 version?

![image](https://user-images.githubusercontent.com/24741439/124689699-8c839500-df0b-11eb-9eff-3a80d4996d54.png)

![image](https://user-images.githubusercontent.com/24741439/124689813-c05eba80-df0b-11eb-9ec5-d7023fec0d76.png)

![image](https://user-images.githubusercontent.com/24741439/124689934-0025a200-df0c-11eb-97de-6f747327b0ba.png)

**Comment by Xuzan9396** [comment]
Dockerfile
```

FROM debian:bullseye-slim
LABEL maintainer="otiai10 <otiai10@gmail.com>"

ARG LOAD_LANG=jpn

RUN apt update \
    && apt install -y \
      ca-certificates \
      libtesseract-dev=4.1.1-2+b1 \
      tesseract-ocr=4.1.1-2+b1 \
      golang=2:1.15~1

ENV GO111MODULE=on
ENV GOPATH=${HOME}/go
ENV PATH=${PATH}:${GOPATH}/bin

# ADD . $GOPATH/src/github.com/otiai10/ocrserver
# WORKDIR $GOPATH/src/github.com/otiai10/ocrserver
# RUN go get -v ./... && go install .

# Load languages
RUN if [ -n "${LOAD_LANG}" ]; then apt-get install -y tesseract-ocr-${LOAD_LANG}; fi

# ENV PORT=8080
# CMD ["ocrserver"]
```

error
docker build  -t orc4.1.1 

![image](https://user-images.githubusercontent.com/24741439/124690796-4a5b5300-df0d-11eb-8892-1534de3abf5c.png)

**Comment by otiai10** [comment]
As I understand it, you are trying to create a Dockerfile with Tesseract 4.1.1, but not working.
Is it right?

**Comment by otiai10** [comment]
it works for me

```dockerfile
FROM debian:bullseye-slim

RUN apt-get update -qq
RUN apt-get install -y \
  git \
  golang \
  libtesseract-dev=4.1.1-2.1 \
  tesseract-ocr-eng

ENV GOPATH=/root/go

ADD . ${GOPATH}/src/github.com/otiai10/gosseract
WORKDIR ${GOPATH}/src/github.com/otiai10/gosseract

RUN tesseract --version

CMD ["go", "test", "-v", "./..."]
```
