### ISSUE TITLE
fatal error: tesseract/baseapi.h: No such file or directory

### ISSUE THREAD

**Issue by hajsf** [otiai10/gosseract#223]
I installed the latest version 5.0.0-alpha of tesseract-ocr for windows as [recommended](https://github.com/UB-Mannheim/tesseract/wiki#tesseract-installer-for-windows).

While running:
```bash
PS D:\> go get -t github.com/otiai10/gosseract
```
I got the error:
```bash
# github.com/otiai10/gosseract
tessbridge.cpp:5:10: fatal error: tesseract/baseapi.h: No such file or directory
 #include <tesseract/baseapi.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
````

I know below can be used as a workaround solution, but would like to use this package:
```go
cmd := exec.Command(`C:\Program Files\Tesseract-OCR\tesseract.exe`, "image_name", "output")
// It saves the result in output.txt file
```

**Comment by otiai10** [comment]
https://github.com/otiai10/gosseract/search?q=baseapi.h&type=issues

**Comment by sardorgo** [comment]
I also have the same problem
