### ISSUE TITLE
fatal error test

### ISSUE THREAD

**Issue by alesjr** [otiai10/gosseract#225]
I have a problem running the test using the dockerfile, when it calls the test the following errors appear:

`go: github.com/otiai10/mint@v1.3.2 requires
        github.com/otiai10/curr@v1.0.0 requires
        github.com/otiai10/mint@v1.3.0: missing go.sum entry; to add it:
        go mod download github.com/otiai10/mint
go: github.com/otiai10/mint@v1.3.2 requires
        github.com/otiai10/curr@v1.0.0 requires
        github.com/otiai10/mint@v1.3.0: missing go.sum entry; to add it:
        go mod download github.com/otiai10/mint`

The application works normally, however I want to put the application inside the docker container and it is not working, even using its Dockerfile. Can you help me?

**Comment by otiai10** [comment]
`go env`, please

**Comment by otiai10** [comment]
closing due to no-reply
