### ISSUE TITLE
go get -t github.com/otiai10/goserract tesseract/baseapi.h: No such file or directory

### ISSUE THREAD

**Issue by umutozgur** [otiai10/gosseract#226]
> This text is generated based on `ISSUE_TEMPLATE.md`. The issue reporter must read and remove this block before submitting.

# Summary

go get -t github.com/otiai10/gosseract
# github.com/otiai10/gosseract
tessbridge.cpp:5:10: fatal error: tesseract/baseapi.h: No such file or directory
    5 | #include <tesseract/baseapi.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

# Reproducibility

## Reproducibility Frequency

- XX%

## Reproducible Dockerfile

```dockerfile
 docker is not installed

Otherwise, describe how to reproduce

1. `foo bar`
2. `spam ham`
3. `hoge fuga`

# Environment

uname -a
```
MINGW64_NT-10.0-19041 DESKTOP-BBNPNAM 3.1.7-340.x86_64 2021-03-26 22:17 UTC x86_64 Msys
```
go env
```
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\dell\AppData\Local\go-build
set GOENV=C:\Users\dell\AppData\Roaming\go\env  
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\AutommateProject\Go\pkg\mod   
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\AutommateProject\Go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\dell\workspace\go\tessetact\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\dell\AppData\Local\Temp\go-build605321102=/tmp/go-build -gno-record-gcc-switches
```
go version
```
go version go1.15.6 windows/amd64
```
tesseract --version
```
bash: tesseract: command not found

**Comment by otiai10** [comment]
Tesseract is not installed
