### ISSUE TITLE
Too many open files (FD > /dev/pts/0)

### ISSUE THREAD

**Issue by Slavchev070720** [otiai10/gosseract#228]
# Summary
There's a problem with this package, when working with a lot of images. I use Tesseract to process some very small sized png images one at a time and when my program reach around ~970th image it start to throw error `too many opend files`. In `/proc/{PID}/fd` i can see that during the process it keeps opening new file descriptors and all of them point to `/dev/pts/0`. My `ulimit -n` is `1024` so it makes sens that at around 970th image reaches the max file descriptors. I am absolutly sure this ishappening because of gosseract library. I saw there was the same issue opend before https://github.com/otiai10/gosseract/issues/198 but there was no answer. NOTE: on `go build` it throws a warning
```
# github.com/otiai10/gosseract
tessbridge.cpp: In function ‘int Init(TessBaseAPI, char*, char*, char*, char*)’:
tessbridge.cpp:46:10: warning: ignoring return value of ‘FILE* freopen(const char*, const char*, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
   46 |   freopen("/dev/null", "a", stderr);
      |   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
tessbridge.cpp:60:10: warning: ignoring return value of ‘FILE* freopen(const char*, const char*, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
   60 |   freopen("/dev/null", "a", stderr);
      |   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
```
I think this could be releated to the problem
# Reproducibility
1. create `tesseractClient = gosseract.NewClient()`
2. create `httpClient = http.Client{}`
3. foreach list with image url
4. for each itereation get the image bytes from httpclient body and then I CLOSE the body.
5. Pass the image bytes to `gosseract.SetImageFromBytes()`
6. Get text by `tesseractClient.Text()`
7. After foreach `tesseractClient.Close()`
## Reproducibility Frequency
- 100%
# Environment
```
uname -a
Linux slavchev-ubuntu 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
```
go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/slavchev/.cache/go-build"
GOENV="/home/slavchev/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/slavchev/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/slavchev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1197784976=/tmp/go-build -gno-record-gcc-switches"
```
```
go version

go version go1.16.4 linux/amd64
```
```
tesseract --version

tesseract 4.1.1
 leptonica-1.79.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.3) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found SSE
 Found libarchive 3.4.0 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.4
```
```
go mod

github.com/antchfx/htmlquery v1.2.4 // indirect
github.com/otiai10/gosseract v2.2.1+incompatible // indirect
github.com/otiai10/mint v1.3.3 // indirect
github.com/sirupsen/logrus v1.8.1 // indirect
golang.org/x/net v0.0.0-20211020060615-d418f374d309 // indirect
```

**Comment by otiai10** [comment]
Thank you. I found this commit https://github.com/otiai10/gosseract/commit/47a6c298b1de41dfe0fc92b2c043dd48be4c5f98 after v2.2.1.

Try v2.2.2 or newer.
Let me know when it fixes.

**Comment by Slavchev070720** [comment]
I update to v2.2.4 and now it works. Also the build warning massage disapeared.Thanks.
`go get github.com/otiai10/gosseract/v2@v2.2.4`
