### ISSUE TITLE
SetImageFromBytes from gocv.mat Image format ?

### ISSUE THREAD

**Issue by AlexMcGopher** [otiai10/gosseract#235]
# Summary

Is the usage of SetImageFromBytes possible with a gocv.mat ?
What conversion do I have to to between the gocv.mat and 
the []byte input image of SetImageFromBytes ? 
Currently I save the mat to a Image file, and use SetImage
but it must be possible without using a Imagefile....

**Comment by AlexMcGopher** [comment]
Would be great if I get at least a small reaction to my question..

**Comment by otiai10** [comment]
Do you mean this?
https://github.com/hybridgroup/gocv/blob/5730c4cf12d5fb4590fb7c97db8ed50c7020cc32/core.go#L183-L188

**Comment by AlexMcGopher** [comment]
Exactly, this is what I am talking about. Sorry for being unprecise in this point.

**Comment by otiai10** [comment]
As of now, I would not fix this package to adjust to another specific package.
I would recommend you to find a way to extract `[]byte` from `gocv.Mat`.

What do you think?

**Comment by Shinora007** [comment]
I created `image.Image` object from `gocv.Mat`.
Then got encoded bytes of `image.Image` using `png.Encode`
These encoded bytes are getting accepted by  gosseract client for use case.

`	client := gosseract.NewClient()
	defer client.Close()

	img := gocv.IMRead("./processed_image.png", gocv.IMReadColor)
	defer img.Close()

	pngImg, _ := img.ToImage()

	buff := new(bytes.Buffer)
	_ = png.Encode(buff, pngImg)

	// client.SetImage("./processed_image.png")
	client.SetImageFromBytes(buff.Bytes())
`
