### ISSUE TITLE
failed to initialize TessBaseAPI with code -1:

### ISSUE THREAD

**Issue by langxlm** [otiai10/gosseract#240]
> This text is generated based on `ISSUE_TEMPLATE.md`. The issue reporter must read and remove this block before submitting.

# Summary

- I install gosseract at win10 . use MSYS2 with Mingw64 to install tesseract , leptonica module。 and finally install gosseract use command 'go get -t go get -t github.com/otiai10/gosseract/v2 '

when i build my test project success , eventually throw a exception : `failed to initialize TessBaseAPI with code -1: '

then I go to the install directory at go path ,  run the go test , also get the same error ：
all_test.go:144
        Expected to be  `<nil>`
        But actual      `failed to initialize TessBaseAPI with code -1: `

I can do nothing , becasue there are haven't any message with that code . 
pls help ! 3q !

# Reproducibility

## Reproducibility Frequency

- 100%

## Reproducible Dockerfile

```dockerfile
FROM your-os:your-version
# Describe how to reproduce your problem
# on your environment
```

Otherwise, describe how to reproduce

# Environment

win10 

uname -a
```

```
go env
# go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\langxli\AppData\Local\go-build
set GOENV=C:\Users\langxli\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\langxli\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\langxli\go;D:\work\brick\brick_app_project
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\langxli\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=D:\msys64\tmp\go-build2794601340=/tmp/go-build -gno-record-gcc-switches

```
go version
# go version
go version go1.17 windows/amd64


```
tesseract --version
# tesseract --version
tesseract 4.1.1
 leptonica-1.81.1
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 2.0.6) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.2 : libopenjp2 2.4.0

**Comment by edhoguntur** [comment]
@langxlm , could you explain how to set TESSDATA_PREFIX in correct path?

**Comment by langxlm** [comment]
@edhoguntur
need to declare the training data directory in system env . 
export TESSDATA_PREFIX=/mingw64/share/tessdata    ( mingw64 )
set TESSDATA_PREFIX=D:\msys64\mingw64\share\tessdata    (windows directly)

**Comment by langxlm** [comment]
v2 version , can set the TessdataPrefix in or code, not need the set env anymore, close now!
