### ISSUE TITLE
fatal error: 'tesseract/version.h' file not found & ld-elf.so.1: /usr/local/lib/libtesseract.so.5: Undefined symbol "__kmpc_global_thread_num"

### ISSUE THREAD

**Issue by frankble** [otiai10/gosseract#242]
After updating the dev environment to freebsd 12.3 and rebuilding a project i stumbled about two problems:

1. After "go get -t github.com/otiai10/gosseract/v2" i got the error "/usr/local/include/tesseract/baseapi.h:32:10: fatal error: 'tesseract/version.h' file not found"
2. After compiling my project and run a test it shows "ld-elf.so.1: /usr/local/lib/libtesseract.so.5: Undefined symbol "__kmpc_global_thread_num"

I fixed problem 1 by editing the the file "baseapi.h" and changed the line "#include <tesseract/version.h>" to "#include "version.h" but this should work without editing. (Also adding "export CPLUS_INCLUDE_PATH=/usr/local/include/:${CPLUS_INCLUDE_PATH}" fixed it)
I don't found a sollution for problem 2 - up to now.

# Environment

```
FreeBSD dev 12.3-RELEASE FreeBSD 12.3-RELEASE r371126 GENERIC  amd64
```

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="freebsd"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/root/go/src/fbis.ch/ocrserver/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2480167296=/tmp/go-build -gno-record-gcc-switches"
```

```
go version go1.17.5 freebsd/amd64
```

```
tesseract 5.0.0
 leptonica-1.76.0
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 2.1.2) : libpng 1.6.37+apng : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.1
 Found OpenMP 201511
 Found libarchive 3.5.2 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.5.0
 Found libcurl/7.80.0 OpenSSL/1.1.1l zlib/1.2.11 libssh2/1.10.0 nghttp2/1.46.0
```

**Comment by frankble** [comment]
I opened a issue for problem 2 also in the tesseract project [https://github.com/tesseract-ocr/tesseract/issues/3777](url) but they told me its a gosseract issue.
Can some point me to the path to solve this issue?

**Comment by otiai10** [comment]
#40 might help

**Comment by otiai10** [comment]
```
-fopenmp
```

it works. See https://github.com/otiai10/gosseract/blob/main/preprocessflags_freebsd.go#L3

Here I close this issue. Thank you for sharing your problem. It helped me a lot.
