### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by NSObjects** [otiai10/gosseract#256]
Undefined symbols for architecture arm64:
  "_curl_easy_cleanup", referenced from:
      tesseract::TessBaseAPI::ProcessPagesInternal(char const*, char const*, int, tesseract::TessResultRenderer*) in libtesseract.a(libtesseract_la-baseapi.o)
  "_curl_easy_init", referenced from:
      tesseract::TessBaseAPI::ProcessPagesInternal(char const*, char const*, int, tesseract::TessResultRenderer*) in libtesseract.a(libtesseract_la-baseapi.o)
  "_curl_easy_perform", referenced from:
      tesseract::TessBaseAPI::ProcessPagesInternal(char const*, char const*, int, tesseract::TessResultRenderer*) in libtesseract.a(libtesseract_la-baseapi.o)
  "_curl_easy_setopt", referenced from:
      tesseract::TessBaseAPI::ProcessPagesInternal(char const*, char const*, int, tesseract::TessResultRenderer*) in libtesseract.a(libtesseract_la-baseapi.o)
  "_curl_easy_strerror", referenced from:
      tesseract::TessBaseAPI::ProcessPagesInternal(char const*, char const*, int, tesseract::TessResultRenderer*) in libtesseract.a(libtesseract_la-baseapi.o)
  "_vDSP_dotpr", referenced from:
      tesseract::DotProductAccelerate(float const*, float const*, int) in libtesseract.a(libtesseract_la-simddetect.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

FAIL    github.com/otiai10/gosseract/v2 [build failed]
FAIL

# Environment

```
uname -a
```
MacBook-Air M2
Darwin MacBook-Air.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:07 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8110 arm64

```
go env
```
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOOS="darwin"
GOTMPDIR=""
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lv/q3jg40wx63bg8qd841s6n8d40000gn/T/go-build84910293=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
go version
```
go version go1.18.3 darwin/arm64
```
tesseract --version
```
tesseract 5.2.0
 leptonica-1.82.0
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 2.1.3) : libpng 1.6.38 : libtiff 4.4.0 : zlib 1.2.11 : libwebp 1.2.4 : libopenjp2 2.5.0
 Found NEON
 Found libarchive 3.6.1 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.5.2
 Found libcurl/7.79.1 SecureTransport (LibreSSL/3.3.6) zlib/1.2.11 nghttp2/1.45.1

**Comment by otiai10** [comment]
@NSObjects please note how you solved it

**Comment by NSObjects** [comment]
@otiai10  clean homebrew and reinstall 

`
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
`

delete /usr/local/Cellar

I  use mac migration assistant to migrate old data from intel mac, so the system contains some x86  lib. 

best reinstall system, clean old data

**Comment by otiai10** [comment]
Thank you. That would be super appreciated by people who will face the same issue.

❤️
