### ISSUE TITLE
Tesseract 5.0: error while loading shared libraries: libtesseract.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Adrian147** [otiai10/gosseract#258]
# Summary

- an `error while loading shared libraries: libtesseract.so.4: cannot open shared object file: No such file or directory` is thrown on running gotesseract on a Clear Linux with tesseract instance. 
- Is Gotesseract compatible with tesseract 5.0?

# Reproducibility

## Reproducibility Frequency

- 100%

## Reproducible Dockerfile

```dockerfile
FROM clearlinux/tesseract-ocr:latest

./test
```

1. Here `test` is simply a Main.go with a gosseract import

# Environment

```
Linux _ 5.14.0-1054-oem #61-Ubuntu SMP Fri Oct 14 13:05:50 UTC 2022 x86_64 GNU/Linux
```

```
go version go1.19 linux/amd64
```

```
tesseract 5.0.0
 leptonica-1.80.0
  libjpeg 6b (libjpeg-turbo 2.0.6) : libpng 1.6.38 : libtiff 4.4.0 : zlib 1.2.12.1-motley : libwebp 1.2.4
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found OpenMP 201511
 Found libarchive 3.6.1 zlib/1.2.12.1-motley liblzma/5.2.7 bz2lib/1.0.8 libzstd/1.5.2
 Found libcurl/7.86.0 OpenSSL/3.0.7 zlib/1.2.12.1-motley zstd/1.5.2 nghttp2/1.50.0
```
# Note
- I can add additional information if needed to solve this issue, Thanks!

**Comment by otiai10** [comment]
This code works fine

**Comment by otiai10** [comment]
This code works fine https://github.com/otiai10/gosseract/pull/259/files

**Comment by Adrian147** [comment]
Thank you for the test!
it worked
