### ISSUE TITLE
Fail on GCP App Engine deployment

### ISSUE THREAD

**Issue by zidianlyu** [otiai10/gosseract#263]
# Summary
Any chances that we can have a fixed lib and get rid of the issue without the need to `brew install tesseract`?
I am trying to deploy a demo on `GCP App Engine`.
I can make it works **locally**, but cannot deploy the project to cloud. Any suggestions?
The followings are the error
```
ERROR: (gcloud.app.deploy) Error Response: [9] Cloud build xxx status: FAILURE
#github.com/otiai10/gosseract
tessbridge.cpp:5:10: fatal error: tesseract/baseapi.h: No such file or directory
#include <tesseract/baseapi.h>
^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

# Reproducibility Frequency
- 100%

**Comment by otiai10** [comment]
Because you need dev files of tesseract and leptonica to build the go app with gosseract, you are basically required to do something like `apt-get install libtessearct-dev` for debian, `dnf install tesseract-devel` for centos, `apk add tesseract-ocr-dev` for alpine, or `brew install tesseract` for darwin.

Given that, you have 3 options to make it run on your cloud environment (regarding you're using GCP):

1. Use [flexible environment of GAE/Go and Docker](https://cloud.google.com/appengine/docs/flexible/custom-runtimes/about-custom-runtimes) on it.
2. Use [Cloud Run and Docker](https://cloud.google.com/run/) on it.
3. Include all required C/C++ source code into your project and tell cgo to build with them [See here](https://pkg.go.dev/cmd/cgo)

**Comment by zidianlyu** [comment]
Thanks for the suggestion! 
Seems like the most efficient approach will be just deploy it with a docker and Cloud Run.

**Comment by zidianlyu** [comment]
Sorry, I am still encounter some problem on the Docker build on this.

But thanks so much for the explanation earlier, I decided to try and use [Cloud Run and Docker](https://cloud.google.com/run/) on it.

Here is my docker file:
```shell
FROM golang:1.19-alpine
WORKDIR /app
RUN apk add tesseract-ocr
RUN apk add tesseract-ocr-dev
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN go build -o ./out/dist .
CMD ./out/dist
```

Here is the command I run to build the image:
```shell
docker build -t ocrdemo .
```

And here are the error I received during the building:
```shell
[+] Building 13.7s (13/13) FINISHED                                              
 => [internal] load build definition from Dockerfile                        0.0s
 => => transferring dockerfile: 238B                                        0.0s
 => [internal] load .dockerignore                                           0.0s
 => => transferring context: 2B                                             0.0s
 => [internal] load metadata for docker.io/library/golang:1.19-alpine       0.6s
 => [1/9] FROM docker.io/library/golang:1.19-alpine@sha256:a9b24b67dc83b33  0.0s
 => [internal] load build context                                           0.0s
 => => transferring context: 567B                                           0.0s
 => CACHED [2/9] WORKDIR /app                                               0.0s
 => CACHED [3/9] RUN apk add tesseract-ocr                                  0.0s
 => [4/9] RUN apk add tesseract-ocr-dev                                     1.4s
 => [5/9] COPY go.mod .                                                     0.0s
 => [6/9] COPY go.sum .                                                     0.0s
 => [7/9] RUN go mod download                                               7.7s
 => [8/9] COPY . .                                                          0.0s
 => ERROR [9/9] RUN go build -o ./out/dist .                                3.9s
------
 > [9/9] RUN go build -o ./out/dist .:
#13 0.712 # github.com/otiai10/gosseract
#13 0.712 cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH
------
executor failed running [/bin/sh -c go build -o ./out/dist .]: exit code: 2
```

Seems like I am still getting dependency error:
```
 > [9/9] RUN go build -o ./out/dist .:
#13 0.712 # github.com/otiai10/gosseract
#13 0.712 cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH
```

@otiai10 Any suggestions to possibly resolve this?

**Comment by otiai10** [comment]
it says `C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH`

**Comment by otiai10** [comment]
Since you look you're using alpine, please check it out https://github.com/otiai10/gosseract/blob/main/test/runtimes/alpine.Dockerfile

**Comment by zidianlyu** [comment]
@otiai10 Thanks!! That was working perfectly fine!
