### ISSUE TITLE
leptonica

### ISSUE THREAD

**Issue by zzdboy** [otiai10/gosseract#274]
> This text is generated based on `ISSUE_TEMPLATE.md`. The issue reporter must read and remove this block before submitting.

# Summary
`client := gosseract.NewClient()
defer client.Close()
client.SetImage("1.jpg")
text, _ := client.Text()
fmt.Println(text)`

# command-line-arguments
D:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running g++ failed: exit status 1
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -llept: No such file or directory
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -llept: No such file or directory
collect2.exe: error: ld returned 1 exit status

# Reproducibility

## Reproducibility Frequency

- XX%

## Reproducible Dockerfile

```dockerfile
FROM your-os:your-version
# Describe how to reproduce your problem
# on your environment
```

Otherwise, describe how to reproduce

1. `foo bar`
2. `spam ham`
3. `hoge fuga`

# Environment

```
uname -a
```

```
go env
```
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=E:\Go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\Go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\Go\src\test\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\Administrator\AppData\Local\Temp\go-build1332072867=/tmp/go-build -gno-record-gcc-switches
```
go version
```
go version go1.20.3 windows/amd64
```
tesseract --version
```
tesseract 5.3.1
 leptonica-1.83.1
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 2.1.4) : libpng 1.6.39 : libtiff 4.5.0 : zlib 1.2.13 : libwebp 1.3.0 : libopenjp2 2.5.0
 Found AVX512BW
 Found AVX512F
 Found AVX512VNNI
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found OpenMP 201511
 Found libarchive 3.6.2 zlib/1.2.13 liblzma/5.2.9 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.2
 Found libcurl/8.0.1 OpenSSL/3.1.0 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.3) libssh2/1.10.0 nghttp2/1.52.0

**Comment by zzdboy** [comment]
tesseract -l chi_sim .\1.jpg 1

直接运行命令是可以成功的

**Comment by Grelo4ka** [comment]
I am also getting this error

**Comment by otiai10** [comment]
https://github.com/otiai10/gosseract/blob/main/test/runtimes/mingw.Dockerfile
