### ISSUE TITLE
undefined: gosseract.NewClient

### ISSUE THREAD

**Issue by leadinglydevelopment** [otiai10/gosseract#283]
> This text is generated based on `ISSUE_TEMPLATE.md`. The issue reporter must read and remove this block before submitting.

# Summary

- I'm getting the error of undefined: gosseract.NewClient even if I install it

**Comment by EnterNameHere7** [comment]
same

**Comment by BacelarVitor** [comment]
@leadinglydevelopment @EnterNameHere7 which go version are you guys using?

**Comment by paulwaldmann** [comment]
@BacelarVitor, I've experienced the same issue. Downgrading to v1.18 (as per [go.mod](https://github.com/otiai10/gosseract/blob/main/go.mod)) fixed the issue.

It'd be nice to see support for v1.21👍🏻

**Comment by paulwaldmann** [comment]
@BacelarVitor, I've experienced the same issue. Downgrading to v1.18 (as per [go.mod](https://github.com/otiai10/gosseract/blob/main/go.mod)) initially fixed the linter, now I can see the function details, but running the code continues to return the same error. The client.go returns tons of undefined errors.

![image](https://github.com/otiai10/gosseract/assets/32001342/52b1a06c-8665-48af-85bf-4eebfcef672f)

**Comment by awaisqarni91** [comment]
Having same issue.

**Comment by TheKaese** [comment]
Same issue here. Cannot compile and just says "undefined: gosseract.NewClient". I'm using `go get -t github.com/otiai10/gosseract/v2` per the readme.

**Comment by marcelovcpereira** [comment]
Same here

**Comment by zikkuratti** [comment]
+1

**Comment by liuweidada** [comment]
+1，Me too，go-version 1.19

**Comment by zikkuratti** [comment]
i think problem is go make some bridge to C tesseract library, but our system haven't api headers needed to open client - need to install tesseract libraries

**Comment by hirokimoto** [comment]
@zikkuratti any idea how to install tesseract libraries on windows? I followed the documents, but no luck.

**Comment by otiai10** [comment]
Hi guys, thank you for raising the issue.
Though we don't have much information about the condition to reproduce and couldn't provide an exact solution, please refer to this folder as examples to setup this software on several common platforms.

https://github.com/otiai10/gosseract/tree/main/test/runtimes

Hope it helps

**Comment by liuweidada** [comment]
> 我认为问题是要与 C tesseract 库建立一些桥梁，但我们的系统没有打开客户端所需的 api 标头 - 需要安装 tesseract 库

I did this and testseract is runnable, but still reporting an error

**Comment by zikkuratti** [comment]
> @zikkuratti any idea how to install tesseract libraries on windows? I followed the documents, but no luck.

i think tesseract docs be helpfull forget about go on this time? i try fix it soon now im make some python stuff here

**Comment by otiai10** [comment]
Hi all,

This issue doesn't provide enough information for a deeper investigation or effective communicate on the thread.
Please provide more information as per the [`ISSUE_TEMPLATE`](https://github.com/otiai10/gosseract/blob/main/ISSUE_TEMPLATE.md). If not, I will close this issue in next 3 days.

Thank you.

**Comment by xinaxiny** [comment]
这个问题依旧没办法解决吗

**Comment by joshua86z** [comment]
``import "C"``   is reason

if you set ``GOOS=linux; GOARCH=amd64``
if must set ``CGO_ENABLED=1``
