### ISSUE TITLE
fatal error: leptonica/allheaders.h: No such file or directory

### ISSUE THREAD

**Issue by jorgeupx** [otiai10/gosseract#284]
> This text is generated based on `ISSUE_TEMPLATE.md`. The issue reporter must read and remove this block before submitting.

# Summary

- I cannot get gosseact to run since I get this error every time

Operative System:

- Windows 11

- How am I running it

I've tried all possible ways, installed leptonica with powershell, then adding path to the allheaders.h folder, same thing with plenty other installers like MSYS2 and others, I really can't get this to work, is there any alternative or any open sourced api using gosseract to not get this every time I try to run it, thanks

**Comment by jqrd** [comment]
I was facing the same error on MacOS, found a solution here https://github.com/otiai10/gosseract/issues/234. Leaving it here in case a solution for Windows is found there.

**Comment by FeverKing** [comment]
Same in Windows 10 23H2.

**Comment by cplasfwst** [comment]
同样的问题，win11 ，我找了很多问题都没有找到答案

**Comment by gethoopp** [comment]
I was fix this problem with this  (I use macOS sequoia) (go 1.24)

add this to your .zshrc 

export CGO_CXXFLAGS="-I/opt/homebrew/Cellar/leptonica/1.85.0/include -I/opt/homebrew/Cellar/tesseract/5.5.1/include"
export CGO_LDFLAGS="-L/opt/homebrew/Cellar/leptonica/1.85.0/lib -L/opt/homebrew/Cellar/tesseract/5.5.1/lib"
