### ISSUE TITLE
tessbridge.cpp:5:10: fatal error: 'leptonica/allheaders.h' file not found

### ISSUE THREAD

**Issue by dr-sharon** [otiai10/gosseract#286]
Hey ,

I have this issues when im tying to build my code.

github.com/otiai10/gosseract/v2
tessbridge.cpp:5:10: fatal error: 'leptonica/allheaders.h' file not found

go version
go version go1.21.0 darwin/amd64

go env

GO111MODULE='auto'
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/kong/Library/Caches/go-build'
GOENV='/Users/kong/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/kong/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/kong/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct/'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/kong/repositories/projects/testocr/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/x1/3_w5bjps145btsd2t3s25gf80000gn/T/go-build2258385787=/tmp/go-build -gno-record-gcc-switches -fno-common'

**Comment by otiai10** [comment]
* brew install tesseract leptonica
* go get -u -v github.com/otiai10/gosseract/v2@v2.4.1
