### ISSUE TITLE
'tesseract/baseapi.h' file not found

### ISSUE THREAD

**Issue by otiai10** [otiai10/gosseract#40]
```
% go test ./...
# github.com/otiai10/gosseract/tesseract
tesseract/tess.cpp:1:10: fatal error: 'tesseract/baseapi.h' file not found
FAIL    github.com/otiai10/gosseract [build failed]
```

**Comment by martinlindhe** [comment]
on osx, this is solved using homebrew: brew install tesseract

**Comment by pindamonhangaba** [comment]
Need to install `libleptonica-dev` and `libtesseract-dev`.

**Comment by otiai10** [comment]
@martinlindhe @pindamonhangaba 

Thanks!

It was a problem caused by updating my machie mavericks to yosemite

**Comment by otiai10** [comment]
s/It was/It might have been/

**Comment by novalagung** [comment]
I experienced same issue here. This error keep showing up even tesseract already installed. Am I missing something?

```bash
$ brew install tesseract
Warning: tesseract-3.04.00 already installed

$ brew install leptonica
Warning: leptonica-1.72 already installed

$ go test ./
# github.com/otiai10/gosseract/tesseract
tesseract/tess.cpp:1:10: fatal error: 'tesseract/baseapi.h' file not found
FAIL	github.com/otiai10/gosseract [build failed]
```

**Comment by otiai10** [comment]
@novalagung 

Thanks for comment.

Did you try this?
https://github.com/otiai10/gosseract/issues/40#issuecomment-100051917

**Comment by novalagung** [comment]
Thanks! is there any reference on how to install `libleptonica-dev` and `libtesseract-dev` on OSX? that would be very helpful for me

**Comment by otiai10** [comment]
how about `brew uinstall` and install again?

**Comment by otiai10** [comment]
MacOSX 10.10.5

```
$ go test ./...
# github.com/otiai10/gosseract/tesseract
tesseract/tess.cpp:1:10: fatal error: 'tesseract/baseapi.h' file not found
FAIL	github.com/otiai10/gosseract [build failed]
```

```
$ brew search tesseract
tesseract
$ brew search leptonica
leptonica
homebrew/versions/leptonica169
$ brew install tesseract
==> Installing dependencies for tesseract: jpeg, libtiff, libpng, leptonica
==> Installing tesseract dependency: jpeg
==> Downloading https://homebrew.bintray.com/bottles/jpeg-8d.yosemite.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring jpeg-8d.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/jpeg/8d: 18 files, 776K
==> Installing tesseract dependency: libtiff
==> Downloading https://homebrew.bintray.com/bottles/libtiff-4.0.6.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libtiff-4.0.6.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libtiff/4.0.6: 259 files, 3.9M
==> Installing tesseract dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.18.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libpng-1.6.18.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.18: 17 files, 1.2M
==> Installing tesseract dependency: leptonica
==> Downloading https://homebrew.bintray.com/bottles/leptonica-1.72.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring leptonica-1.72.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/leptonica/1.72: 48 files, 5.6M
==> Installing tesseract
==> Downloading https://homebrew.bintray.com/bottles/tesseract-3.04.00.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring tesseract-3.04.00.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/tesseract/3.04.00: 74 files, 39M
```

```
$ go test ./...
ok  	github.com/otiai10/gosseract	1.422s
?   	github.com/otiai10/gosseract/tesseract	[no test files]
ok  	github.com/otiai10/gosseract/tesseract/test	0.454s
```

**Comment by carbocation** [comment]
On El Capitan, installation of gosseract does not seem to work:

```sh
$ brew install tesseract
==> Installing dependencies for tesseract: leptonica
==> Installing tesseract dependency: leptonica
==> Downloading https://homebrew.bintray.com/bottles/leptonica-1.72.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring leptonica-1.72.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/leptonica/1.72: 48 files, 5.4M
==> Installing tesseract
==> Downloading https://homebrew.bintray.com/bottles/tesseract-3.04.00.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring tesseract-3.04.00.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/tesseract/3.04.00: 74 files, 39M

$ go get github.com/otiai10/gosseract
# github.com/otiai10/gosseract/tesseract
github.com/otiai10/gosseract/tesseract/tess.cpp:1:10: fatal error: 'tesseract/baseapi.h' file not found
```

**Comment by carbocation** [comment]
Actually, I think I have a solution. This problem can occur when the command-line developer tools for Xcode are not installed, or when you upgrade Xcode.

To fix, do the following:

```sh
brew remove tesseract
brew remove leptonica
xcode-select --install
brew install tesseract
go get github.com/otiai10/gosseract
```

This worked for me.

**Comment by otiai10** [comment]
Thank you! :beer:

**Comment by novalagung** [comment]
+1

**Comment by zhujiarong** [comment]
I follow this command
brew remove tesseract
brew remove leptonica
xcode-select --install
brew install tesseract
go get github.com/otiai10/gosseract

same error

**Comment by otiai10** [comment]
did you get any error output while issuing those commands?

**Comment by geoherna** [comment]
+1 

brew remove tesseract
brew remove leptonica
xcode-select --install
brew install tesseract
go get github.com/otiai10/gosseract

worked like a charm.

**Comment by zsq2010** [comment]
how about on windows?

**Comment by otiai10** [comment]
@zsq2010 did you get the same error? Put that error here please. I'm sorry I'm not so familiar with Windows, just I'm reading https://github.com/tesseract-ocr/tesseract/wiki#windows.

**Comment by liu-xuewen** [comment]
windows get the same error? I put here. please help.
```
# github.com/otiai10/gosseract/tesseract
F:\mygo\src\github.com\otiai10\gosseract\tesseract\tess.cpp:1:31: fatal error: tesseract/baseapi.h: No such file or directory
compilation terminated.
```

**Comment by huehnerhose** [comment]
I try to install gosseract on FreeBSD 11.0. I have tesseract and leptonica installed. My `baseapi.h` is at `/usr/local/include/tesseract/baseapi.h` but I still get: 

    go get github.com/otiai10/gosseract
    # github.com/otiai10/gosseract/tesseract
    tess.cpp:1:10: fatal error: 'tesseract/baseapi.h' file not found

Is there any way to tell where to find the file manually?

**Comment by xgz123** [comment]
> I follow this command
> brew remove tesseract
> brew remove leptonica
> xcode-select --install
> brew install tesseract
> go get github.com/otiai10/gosseract
> 
> same error

same here
I have xcode-select already installed

**Comment by a8568730** [comment]
@martinlindhe @pindamonhangaba

Thanks!

**Comment by wozuo** [comment]
For anybody else experiencing this issue on an M1 mac:
```
CPATH=/opt/homebrew/include  LIBRARY_PATH=/opt/homebrew/lib go get -t github.com/otiai10/gosseract
```

**Comment by TuringJest** [comment]
I have the same problem on a Mac M1 :(  
Installed tesseract with `brew` but get the same error
`tesseract/tess.cpp:1:10: fatal error: 'tesseract/baseapi.h' file not found`

Removing/reinstalling `tesseract` and `leptonica` with brew also didn't help.

Leptonica is available under `opt/homebrew/cellar/leptonica`. I also tried to set the 
`PKG_CONFIG_PATH=:/opt/homebrew/cellar/leptonica/leptonica/1.81.1/lib/pkgconfig:/opt/homebrew/cellar/tesseract/4.1.1/lib/pkgconfig`

But still nothing...

@wozuo how did you get it to work. Did you just export `CPATH` and `LIBRARY_PATH`? I tried that and it also didn't work.

**Comment by sivsivsree** [comment]
> For anybody else experiencing this issue on an M1 mac:
> 
> ```
> CPATH=/opt/homebrew/include  LIBRARY_PATH=/opt/homebrew/lib go get -t github.com/otiai10/gosseract
> ```

This works charm 🚀
