### ISSUE TITLE
Testing on Mac OSX

### ISSUE THREAD

**Issue by prsolucoes** [otiai10/gosseract#44]
I have installed everything and after build the go file with readme example, i have an error:

```ld: warning: ld: warning: ignoring file /usr/local/lib/liblept.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/lib/liblept.dylibignoring file /usr/local/lib/libtesseract.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/lib/libtesseract.dylib```

What can be happen?

**Comment by otiai10** [comment]
Thanks for comment.
It seems you have installed `tesseract` for 64-bit CPU but your PC is i386.
Can you comment your OS version and CPU spec below, please?

**Comment by prsolucoes** [comment]
Sorry, i forgot put the solution. You are correct. After check go env, i see that i have installed go version 386 instead of 64bits version. No more problems.

**Comment by otiai10** [comment]
:+1:
