### ISSUE TITLE
tesseract/baseapi.h: No such file or directory

### ISSUE THREAD

**Issue by tobiassoltermann** [otiai10/gosseract#51]
I'd like to use tesseract with go on Windows 7.

During the installation process, as stated in the docs I execute

```
c:\go\src\proj>go get github.com/otiai10/gosseract
# github.com/otiai10/gosseract/tesseract
C:\go\src\github.com\otiai10\gosseract\tesseract\tess.cpp:1:31: fatal error: tesseract/baseapi.h: No such file or directory
 #include <tesseract/baseapi.h>
                               ^
compilation terminated.
```

And by searching the file system for the header file baseapi.h, I cannot find it.

How can I solve this? Thank you

**Comment by otiai10** [comment]
Can this issue https://github.com/otiai10/gosseract/issues/40 help you?

**Comment by tobiassoltermann** [comment]
No, unfortunately, it didn't. I've seen this before and wouldn't have opened this issue if a solution of #40 worked. In fact I even tried to copy all the dependencies into the tesseract folder. This works until it has to compile freetype.

**Comment by otiai10** [comment]
Happy new year.

I don't know about windows so much, but how did you install tesseract, leptonica and their dev libs?

**Comment by chrispytoes** [comment]
I am also having the exact same error. I installed the Windows binary for tesseract-ocr.

**Comment by quarkey** [comment]
I'm getting the same error with debian jessie 32bit with tesseract installed.

**Comment by otiai10** [comment]
Installing only binary is not enough to let gosseract work. It uses tesseract-ocr library files, as discussed on #40

**Comment by otiai10** [comment]
Hey @tobiassoltermann, @chrispytoes, how did you install tesseract-ocr, and where is the header files of that?

**Comment by tobiassoltermann** [comment]
@otiai10 I'm not sure anymore. I think I installed tesseract and leptonica from the Windows installers. But my project was abandoned, so it's obsolete...

**Comment by otiai10** [comment]
😢 
Thanks anyway for replying
