### ISSUE TITLE
PSM Support?

### ISSUE THREAD

**Issue by dustinwtf** [otiai10/gosseract#52]
Is there a way to edit the PSM argument that gets passed into Tesseract?

**Comment by otiai10** [comment]
Thanks.
I'll try it. But it cannot be supported immediately.

https://tesseract-ocr.googlecode.com/svn/trunk/doc/tesseract.1.html

**Comment by otiai10** [comment]
I'm planning dynamic refactoring, in order to give more tesseract options easily.

**Comment by otiai10** [comment]
tessedit_pageseg_mode

**Comment by otiai10** [comment]
http://tesseract-ocr.github.io/a01278.html#a338d4c8b5d497b5ec3e6e4269d8ac66a

**Comment by otiai10** [comment]
- https://zdenop.github.io/tesseract-doc/classtesseract_1_1_tess_base_a_p_i.html#a15a7a9c1afbba3078a55b4566de891ab
- https://rmtheis.github.io/tess-two/javadoc/com/googlecode/tesseract/android/TessBaseAPI.PageSegMode.html

**Comment by otiai10** [comment]
implemented on [v2/develop](https://github.com/otiai10/gosseract/tree/v2/develop)
