### ISSUE TITLE
Undefined reference to simple.

### ISSUE THREAD

**Issue by kyle-sorensen** [otiai10/gosseract#55]
```
go get github.com/otiai10/gosseract

```

```
/tmp/go-build043179523/github.com/otiai10/gosseract/tesseract/_obj/wrapper.cgo2.o: In function `_cgo_f34bd392845b_Cfunc_simple':
/usr/share/go/src/pkg/github.com/otiai10/gosseract/tesseract/wrapper.go:35: undefined reference to `simple'
collect2: ld returned 1 exit status
```

The build failed during tests because of this error too.

**Comment by otiai10** [comment]
@kyle-sorensen 

Thank you very much.
Can you give me some information below?

1. output of `go version`
2. output of `go env`
3. output of `go clean -x github.com/otiai10/gosseract` and `go build -x github.com/otiai10/gosseract`

**Comment by otiai10** [comment]
no information
