### ISSUE TITLE
Possible to add support for tessedit_write_images config variable?

### ISSUE THREAD

**Issue by james-robson** [otiai10/gosseract#56]
Hi, 

I was reading through the [Tesseract docs here](https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality) on improving the OCR output quality. It mentions that setting the `tessedit_write_images` config variable allows a user to view the input file after initial processing by Tesseract. 

Would it be possible to add this feature to the wrapper? It seems that a combination of `api->SetVariable("tessedit_write_images", writeimages);` and `api->GetThresholdedImage()` in `tess.cpp` would allow saving the .tif file. I attempted this in a branch but I don't have much C++ experience and it didn't seem to work...

Thank you

**Comment by otiai10** [comment]
https://github.com/otiai10/gosseract/commit/3fe7ee5dc1e0e04db46434974abdbdad43556882

It enables to set any variables. I'm not sure but guess it works for the case of `tessedit_write_images`.
