### ISSUE TITLE
test errors: Error opening data file and can't find language

### ISSUE THREAD

**Issue by williamczuba** [otiai10/gosseract#57]
I tried to run the first test, but it failed with the following errors:

```
[wigywizzle@wigywizzle gosseract]$ go test ./...
Error opening data file /usr/share/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.
FAIL    github.com/otiai10/gosseract    0.006s
?       github.com/otiai10/gosseract/tesseract  [no test files]
Error opening data file /usr/share/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.
FAIL    github.com/otiai10/gosseract/tesseract/test     0.006s

```

**Comment by otiai10** [comment]
I hope it can help you
http://stackoverflow.com/questions/14800730/tesseract-running-error

Please add some comment after you try this, thank you

**Comment by otiai10** [comment]
https://github.com/otiai10/docker-tesseract/blob/master/Dockerfile#L56-L61

**Comment by rehman297** [comment]
> I hope it can help you
> http://stackoverflow.com/questions/14800730/tesseract-running-error
> 
> Please add some comment after you try this, thank you

It didn't work for me on windows machine.
I am still getting error:
Error opening data file ./eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!

**Comment by yjjnls** [comment]
@rehman297 I also met the problem in ubuntu. I set TESSDATA_PREFIX but it sitll raised the error. Have you fixed it?

**Comment by otiai10** [comment]
Ubuntu: https://github.com/otiai10/gosseract/blob/master/test/runtimes/ubuntu.Dockerfile
