### ISSUE TITLE
Windows 10 can't run

### ISSUE THREAD

**Issue by xiangshenb** [otiai10/gosseract#62]
My system is windows10 64 bit, my gcc use https://github.com/go-vgo/Mingw,
At first,error is  : tesseract/baseapi.h' file not found ,
Then I went to download class libraries : 
1. tesseract-3.02.02-win32-lib-include-dirs.zip download url https://sourceforge.net/projects/tesseract-ocr-alt/files/
2. leptonica-1.68-win32-lib-include-dirs.zip   download url http://www.leptonica.com/download.html
And then put  this in "Mingw include "  and  "Mingw lib " directory.

Above errors disappear.
but And there's a new mistake.
d:/git/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -llept
d:/git/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ltesseract
collect2.exe: error: ld returned 1 exit status

Spent 2 days, and now do not know how to do, and hope to be resolved, thank you!

**Comment by zosocanuck** [comment]
I am also running into the same issue with cygwin on Windows 10

**Comment by otiai10** [comment]
seems it will help
https://stackoverflow.com/questions/12868808/how-to-tell-c-library-path-in-cygwin-and-mingw
