### ISSUE TITLE
But actual	`No tesseract version is found, supporting 3.02~, 3.03~, 3.04~ and 3.05~`

### ISSUE THREAD

**Issue by jackluo2012** [otiai10/gosseract#68]
[root@localhost gosseract]# go test
/tmp/go-build841552903/gosseract/_test/gosseract.test: error while loading shared libraries: liblept.so.5: cannot open shared object file: No such file or directory
exit status 127
FAIL	gosseract	0.001s
[root@localhost gosseract]# ls /usr/local/lib/
codecs/                liblept.so.5.0.1       libtesseract.so.4
liblept.a              libpython3.6m.a        libtesseract.so.4.0.0
liblept.la             libtesseract.a         pkgconfig/
liblept.so             libtesseract.la        python3.6/
liblept.so.5           libtesseract.so        
[root@localhost gosseract]# ls /usr/local/lib/libtesseract.
libtesseract.a         libtesseract.so        libtesseract.so.4.0.0
libtesseract.la        libtesseract.so.4      
[root@localhost gosseract]# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
[root@localhost gosseract]# go test
Info in bmfCreate: Generating pixa of bitmap fonts from string
Warning. Invalid resolution 0 dpi. Using 70 instead.
Info in bmfCreate: Generating pixa of bitmap fonts from string
Warning. Invalid resolution 0 dpi. Using 70 instead.
Info in bmfCreate: Generating pixa of bitmap fonts from string
Warning. Invalid resolution 0 dpi. Using 70 instead.
all_test.go at line 37
	Expected to be	`42`
	But actual	`03:41:26`
--- FAIL: Test_Must_WithDigest (0.42s)
all_test.go at line 42
	Expected to be	`<nil>`
	But actual	`No tesseract version is found, supporting 3.02~, 3.03~, 3.04~ and 3.05~`
--- FAIL: Test_NewClient (0.01s)
--- FAIL: TestClient_Src (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x520c7d]

goroutine 13 [running]:
testing.tRunner.func1(0xc420069040)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x54a340, 0x8119c0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
gosseract.TestClient_Src(0xc420069040)
	/data/software/src/gosseract/all_test.go:55 +0x3d
testing.tRunner(0xc420069040, 0x57e468)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca
exit status 2
FAIL	gosseract	0.707s

**Comment by otiai10** [comment]
what is the output of `tesseract -v`?

`Client` is, for now, just a command wrapper, requiring available executable bin.

**Comment by jackluo2012** [comment]
[root@localhost src]# tesseract -v
tesseract 4.00.00alpha
 leptonica-1.74.1
  libjpeg 6b (libjpeg-turbo 1.2.90) : libpng 1.5.13 : libtiff 4.0.3 : zlib 1.2.7

 Found AVX
 Found SSE
[root@localhost src]#

**Comment by otiai10** [comment]
then, you can see there is no tesseract versions supported. 4.00.00 is out of range.
