### ISSUE TITLE
Can't build with MinGW

### ISSUE THREAD

**Issue by danielfazlijevic** [otiai10/gosseract#69]
I cannot build with `go build` nor I can ` go get github.com/otiai10/gosseract` ,
I get error: 
`go build github.com/otiai10/gosseract/tesseract: C:\go\pkg\tool\windows_386\cgo.exe: exit status 2`

I installed CGO, tried restarting my pc, nothing works.

**Comment by otiai10** [comment]
How did you installed `cgo`? `cgo` is one of standard components included in initial golang installation itself. Plus, show me outputs of commands bellow

- `go version`
- `go env`

**Comment by danielfazlijevic** [comment]
```

C:\Users\Dell>go version
go version go1.8.3 windows/386

C:\Users\Dell>go env
set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Dell\Desktop\GOLANG Development
set GORACE=
set GOROOT=C:\go
set GOTOOLDIR=C:\go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

```

I used MinGW to install some components.

**Comment by otiai10** [comment]
it might be helpful https://github.com/mattn/go-sqlite3/issues/168
