### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by icobani** [otiai10/gosseract#80]
I want to install package on my mac. but i get a error like this. I checked this file in project i cannot find. I think it is missing.

`go get github.com/otiai10/gosseract`
`# github.com/otiai10/gosseract/tesseract`
`../../otiai10/gosseract/tesseract/tess.cpp:5:10: fatal error: 'tesseract/baseapi.h' file not found`

**Comment by otiai10** [comment]
@icobani needs more information.

How did you install [tesseract](https://github.com/tesseract-ocr/tesseract)?

**Comment by otiai10** [comment]
https://github.com/otiai10/gosseract/issues/40

**Comment by otiai10** [comment]
no updates
