### ISSUE TITLE
Can Gosseract work with QT on Android/iOS?

### ISSUE THREAD

**Issue by greatGregLiu** [otiai10/gosseract#90]
Can Gosseract work with this go-QT: https://github.com/therecipe/qt?

So we can make App with gosseract and go version QT? Scan bank cards then use gosseract OCR? Thanks

**Comment by otiai10** [comment]
@greatGregLiu Thanks for comment.

`gosseract` requires Go itself and Tesseract-OCR library files (shared objects and headers, `tesseract/baseapi.h` for example). If it's possible to install C packages on QT framework and locate library files with being linkable, you might be able to do what you want. As I don't know much about QT, could you show me any small example app working with go-QT?

**Comment by otiai10** [comment]
hope it helps you
https://github.com/otiai10/gosseract/blob/master/test/runtimes/tess3.04_go1.9_MinGW.Dockerfile
